### ISSUE TITLE
Cannot install with node-webkit > 0.8.6 because of node-xpc-connection dependency

### ISSUE THREAD

**Issue by mhle** [sandeepmistry/noble#113]
Hi,

xpc-connection dependency required on OSX does not seem to build correctly for node-webkit > 0.8.6.

Please see https://github.com/sandeepmistry/node-xpc-connection/issues/5

Any help would be highly appreciated.

Thanks,

Michael

**Comment by sandeepmistry** [comment]
Work done in https://github.com/sandeepmistry/node-xpc-connection/pull/6 by @francishart to use nan

@mhle please try latest noble

**Comment by mhle** [comment]
Thanks Sandeep, I worked with Francis to fork noble and xpc-connection any chance we can get these changes into next version?

Thanks,

Michael
