### ISSUE TITLE
Changing linux implementation to use btle.

### ISSUE THREAD

**Issue by edgarsilva** [sandeepmistry/noble#115]
Hi,

We are thinking on changing the Linux implementation to use [btle](https://github.com/jacklund/btle.js) instead of the two compiled tools it uses now (l2cap and hci).

This in order to improve performance, stability and reliability, since spawning these processes and piping them creates inconsistent behavior and drops, besides they are not really async calls, which causes more issues.

What do you think? is this something you might consider pulling in if we make it work with noble?

I'm with [The Hybrid Group](https://github.com/hybridgroup) BTW.

Regards,

**Comment by jacklund** [comment]
My apologies for being so late in responding. Holidays plus work has been keeping me very busy.

I'd love to help out with this.

**Comment by sandeepmistry** [comment]
@deadprogram @edgarsilva any progress on this?

**Comment by deadprogram** [comment]
Hi @sandeepmistry 

Now that BlueZ has just released their dbus support, your original plan seems viable: http://www.bluez.org/release-of-bluez-5-30/

**Comment by sandeepmistry** [comment]
@deadprogram good to know. Let's close this issue for now, please start a new one for dbus support when you are ready.
