### ISSUE TITLE
stderror: execvp()

### ISSUE THREAD

**Issue by ayhoung** [sandeepmistry/noble#123]
I'm on debian/linux and noble was working perfectly yesterday. Unfortunately today I got this error: stderror: execvp(). any idea what's causing it?

**Comment by ayhoung** [comment]
solved: for some reason, I was able to solve this by deleting my node_modules and npm installing again.

**Comment by sandeepmistry** [comment]
@ayhoung do you remember if you changed anything in between runs? Maybe you deleted ``hci-ble``.
