### ISSUE TITLE
Noble stops listening

### ISSUE THREAD

**Issue by doganyazar** [sandeepmistry/noble#129]
Noble seems to stop listening after some non-deterministic time and the only solution I came up with is to call startScanning again (or pkill -SIGUSR2 hci-ble).
Do you have any ideas or suggestions?

**Comment by sandeepmistry** [comment]
@doganyazar what kernel / Linux distro / BlueZ version are you using?

I haven't experienced this behaviour. I would suggest you:

1. add print outs in [hci-ble.c](https://github.com/sandeepmistry/noble/blob/master/src/hci-ble.c)
2. run ```node-gyp rebuild```
3. run with debug on: ```sudo DEBUG=hci-ble <file>.js```

I can help out more once you've done the above ... and provide output.

**Comment by sandeepmistry** [comment]
@doganyazar also wanted to confirm, you are calling startScanning with duplicates set to true, right?
```javascript
noble.startScaning([], true);
```

**Comment by doganyazar** [comment]
Yes, duplicates is set to true. 
I have experienced this behaviour with several BlueZ versions > 5.20 and Debian with kernel > 3.14.

I will dig into this as soon as possible and will try to narrow it down. 
Thanks

**Comment by sandeepmistry** [comment]
@doganyazar sounds good ... it would be good to compare noble behaviour with:

```sh
hcitool lescan --duplicates
```

As they should be making the same calls to the Linux kernel.

**Comment by sandeepmistry** [comment]
@doganyazar any updates on this?

**Comment by doganyazar** [comment]
Sorry apparently I had completely forgotten this :) Just setup an environment for this so will start investigating now!

**Comment by doganyazar** [comment]
It takes couple of days to replicate this and that is why I could not really find anything interesting up to now. But I actively continue checking the running machine. Most probably I need to dig into bluez more to figure out the reason.

**Comment by doganyazar** [comment]
After all these trials, I could only repeat this problem with the Plugable Bluetooth adapter
(http://plugable.com/products/usb-bt4le). I think the dongle gets into some weird state after some time which causes this behaviour. 

I have also seen noble printing
console.log('noble warning: adapter does not support Bluetooth Low Energy (BLE, Bluetooth Smart).');
when this adapter was used in some occasions.

**Comment by sandeepmistry** [comment]
@doganyazar do you have a set of reproducible steps?

**Comment by doganyazar** [comment]
Nope I have no deterministic way of producing it. But I think it has nothing to do with noble since when it happens lescan does not work either giving the following error.

```
$ sudo hcitool lescan
Set scan parameters failed: Input/output error
```

**Comment by sandeepmistry** [comment]
@doganyazar good to know. Can we close this issue?

**Comment by jmaxxz** [comment]
@doganyazar is there any way to detect this condition so scanning can automatically be restarted?

**Comment by doganyazar** [comment]
@jmaxxz  I don't think that callback was ever triggered but I cannot try it now since I do not have the setup anymore. 
Our workaround was to call startScaning every 10 minutes or so. And it worked fine.

**Comment by sandeepmistry** [comment]
https://github.com/sandeepmistry/noble/pull/301 will emit the scan stop if it's triggered by an external program.
