### ISSUE TITLE
NobleJS on NodeWebkit 0.12.0

### ISSUE THREAD

**Issue by mhle** [sandeepmistry/noble#146]
Hi Sandeep, 

I've noticed that I do not longer need to run nw-gyp rebuild when using Noble on the latest nodewebkit (0.12.0) and iojs 1.4.3, just wondering if you had any idea why this is the case? 

Michael

**Comment by sandeepmistry** [comment]
@mhle maybe since they use the same/similar version of v8, the native module built by node-gyp for io.js is compatible with nw.js now.
