### ISSUE TITLE
GAP service hidden on Mac OS X Yosemite

### ISSUE THREAD

**Issue by rene-aguirre** [sandeepmistry/noble#154]
First, I really appreciate what you are doing, keep going!!!!

I was able to confirm by using multiple peripherals products, that Linux shows GAP service characteristics for service discovery results ('uuid': '1800'), same for Generic Attributes ('uuid': '1801'), such items are just hidden in Mac OS X Yosemite.

Maybe related, reading GAP attributes is not possible (device name, appearance are mandatory, try with those please).

Related to reading GAP attributes, I can see that LightBlue reads the GAP device name attribute by issuing an ATT ready type request (start handle = 0x0001, end handle = 0xffff), as pointed out by core specification... so if there is no way Mac shows the service during discovery (so the actual handles can be read) this could be an alternative.

By the way... how do you get the com.apple.blued message id values and parameters (specially posting events to the xpc service)? I'm interested in providing patches (and bindings to Python)

**Comment by sandeepmistry** [comment]
@rene-aguirre yes, OS X 10.10 started behaving more like iOS's CoreBluetooth stack and does not report the GAP attributes.

The handles could be read, but they might not have the same handle number on all devices.

It would be great if you made a BLE library for Python! Checkout [osx-ble-peripheral](https://github.com/sandeepmistry/osx-ble-peripheral). If you [uncomment the XPC_SPY define line](https://github.com/sandeepmistry/osx-ble-peripheral/blob/master/BLEPeripheral/BPAppDelegate.m#L83)  you can see all Central or Peripheral messages sent to blued for the CoreBluetooth API's you call.
