### ISSUE TITLE
readUInt16 not present in characterstic data

### ISSUE THREAD

**Issue by wezside** [sandeepmistry/noble#157]
This is a question. I have read the Cadence Measurement Bluetooth spec and it states that the 'Cumulative Crank Revolutions' should be of type uint16. I'm however only able to use readUInt8 with noble and when I log the data is shows it as such. 

Would this be the device manufacturer not implementing the spec? Or noble?

**Comment by sandeepmistry** [comment]
@wezside I'm guess its a device manufacturer issue.

You're using a Raspberry Pi right? try out ```gatttool``` to see what it reports.

Please follow up on gitter, if you get stuck: https://gitter.im/sandeepmistry/noble
