### ISSUE TITLE
Major and Minor Values?

### ISSUE THREAD

**Issue by kevinits** [sandeepmistry/noble#173]
While scanning, can you read the major and minor values of the peripheral beacons like you can with node-bleacons?

**Comment by sandeepmistry** [comment]
@kevinits I'm trying to keep noble a generic BLE lib. Beacon specifics should go in node-bleacon.

Is there a reason for not using node-bleacon?

**Comment by kevinits** [comment]
No, not really.  I'm just a newbie with bluetooth, trying to figure it all out.  That makes sense.  For my use case, I like the ability in noble to not see all of the duplicates.  In node-bleacon, is that a possibility or do I need to figure out how to filter them out myself?  Thanks for the quick reply.

**Comment by sandeepmistry** [comment]
@kevinits please open an issue for this in the node-bleacon repo.
