### ISSUE TITLE
Indicate whether peripheral.address is random

### ISSUE THREAD

**Issue by LookingSharp** [sandeepmistry/noble#181]
I'd like to know if the MAC address for a peripheral is temporary.  Some devices use a random address.  I'd like to know this because I know the devices I'm looking for have this behavior, so if the address is not random I can ignore it.  If this isn't surfaced on all platforms, can this be added as an environment variable (I'm on Raspian).

**Comment by sandeepmistry** [comment]
@LookingSharp implemented in https://github.com/sandeepmistry/noble/commit/180bf2f5291b008f2d3c23b9fdebe736b9d57d46
