### ISSUE TITLE
Unhandled signals in linux binding

### ISSUE THREAD

**Issue by rosek86** [sandeepmistry/noble#190]
Hi,

It's possible that some signals send to hci-ble.c are not handled, this issue occurs when I try to call stopScanning function and immediately startScanning. There is no signal queue in hci-ble.c, so only one of these signals will be received. The hci-ble.js doesn't wait for confirmation from hci-ble.c that the signal was handled too before emitting scanStart or scanStop events.

Eventually our application stopped to scan for devices at all, even though scanning was enabled at the noble.js layer.

**Comment by sandeepmistry** [comment]
noble now uses bluetooth-hci-socket instead of spawned (hci-ble and l2cap-ble) processes.

This issue should be resolved now.
