### ISSUE TITLE
Communicate with several Bluetooth devices

### ISSUE THREAD

**Issue by shiva02** [sandeepmistry/noble#197]
Hi,
Is it possible to communicate with several Bluetooth devices at the same time ?
And if so would you have an example or an idea ?
Thanks a lot.

Best regard

Shiva

**Comment by sandeepmistry** [comment]
@shiva02 it's pretty much the same as one device.

You just need to continue scanning, instead of stop scanning after you discover one device.

**Comment by shiva02** [comment]
Thanks a lot
