### ISSUE TITLE
Service and Characteristic name not configurable

### ISSUE THREAD

**Issue by sonkrishna** [sandeepmistry/noble#203]
Hi Sandeep,

Hope you are doing great!

We followed your node module and wrote code on BLE and its working. However Service and Characteristic name are not configurable. It's coming like UNKNOWN SERVICE , UNKNOWN CHARACTERISTIC.

Your valuable input will be highly appreciable.

Thanks in advance!

Regards,
Krishna

**Comment by bragma** [comment]
Hi @sonkrishna, I'm not sure about what you are trying to do, but service and characteristic names are defined in lib/characteristics.json and services.json. Have you checked that the service and characteristic UUID you receive from the device are present in those files?

**Comment by sandeepmistry** [comment]
@sonkrishna this is expected behaviour, only Bluetooth SIG approved UUID's have non-unknown name values.

https://developer.bluetooth.org/gatt/Pages/default.aspx
