### ISSUE TITLE
Connect and write to a peripheral without scanning (address and handle is known)

### ISSUE THREAD

**Issue by yasdfgr** [sandeepmistry/noble#213]
Is it possible to connect to a peripheral without scanning?
I have all addresses xx:xx:xx:xx:xx:xx.
How can i do that?

Is it possible to create a peripheral object by my own and simply use the methods connect() and writeHandle()?

**Comment by littlemonkey** [comment]
I also think this function is very valuable!

**Comment by sandeepmistry** [comment]
This is not be possible on OS X, so I haven't implemented it.

Work around for now is to start scanning and check ```peripheral.address``` on discover event.

**Comment by yasdfgr** [comment]
I had the idea to compose a peripheral object on my own - but it seems not so easy. Would it work theoretically?

**Comment by sandeepmistry** [comment]
This enhancement will not work with OS X, closing for now ....
