### ISSUE TITLE
specific nodejs version for noble

### ISSUE THREAD

**Issue by Netfreak25** [sandeepmistry/noble#216]
Hey Sandeep,

I recently bought a dongle to integrate the flower powers into my home system and wanted to use noble/flower-power through my raspberry. I updated the repo and installed nodejs and npm but I was unable to install noble and flower-power.

I had to uninstall nodejs from the repo and install http://nodejs.org/dist/v0.11.12/node-v0.11.12-linux-arm-pi.tar.gz manually in order to get it running.

Are there known dependencies? I haven't found a dependency that claims that a specific version has to be installed.

**Before:**
*root@raspbmc:~# npm install noble*

npm http GET http://registry.npmjs.org/noble
npm http 304 http://registry.npmjs.org/noble

npm ERR! Error: No compatible version found: noble
npm ERR! No valid targets found.
npm ERR! Perhaps not compatible with your version of node?
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
npm ERR!     at next_ (/usr/share/npm/lib/cache.js:438:17)
npm ERR!     at next (/usr/share/npm/lib/cache.js:415:44)
npm ERR!     at /usr/share/npm/lib/cache.js:408:5
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /root/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.12.31
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "noble"
npm ERR! cwd /root
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message No compatible version found: noble
npm ERR! message No valid targets found.
npm ERR! message Perhaps not compatible with your version of node?
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm not ok

*root@raspbmc:~# npm install flower-power*

npm http GET http://registry.npmjs.org/flower-power
npm http 304 http://registry.npmjs.org/flower-power
npm http GET http://registry.npmjs.org/noble-device
npm http GET http://registry.npmjs.org/noble
npm http 304 http://registry.npmjs.org/noble-device
npm ERR! error installing flower-power@0.2.1
npm http 304 http://registry.npmjs.org/noble

npm ERR! Error: No compatible version found: noble-device@'^0.1.2'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","1.0.0","1.0.1","1.0.2"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
npm ERR!     at /usr/share/npm/lib/cache.js:375:15
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /root/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.12.31
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "flower-power"
npm ERR! cwd /root
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message No compatible version found: noble-device@'^0.1.2'
npm ERR! message Valid install targets:
npm ERR! message ["0.1.0","0.1.1","0.1.2","0.1.3","1.0.0","1.0.1","1.0.2"]
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm not ok

**After:**
*root@raspbmc:~# npm install noble*

npm WARN optional dep failed, continuing xpc-connection@0.1.3

> noble@1.0.2 install /root/node_modules/noble
> node-gyp rebuild

make: Entering directory '/root/node_modules/noble/build'
  CC(target) Release/obj.target/hci-ble/src/hci-ble.o
  LINK(target) Release/hci-ble
  CC(target) Release/obj.target/l2cap-ble/src/l2cap-ble.o
  CC(target) Release/obj.target/l2cap-ble/src/utility.o
  LINK(target) Release/l2cap-ble
make: Leaving directory '/root/node_modules/noble/build'
noble@1.0.2 node_modules/noble
├── bplist-parser@0.0.6
└── debug@2.2.0 (ms@0.7.1)

*root@raspbmc:~# npm install flower-power*
npm WARN optional dep failed, continuing xpc-connection@0.1.3

noble@0.3.14 install /root/node_modules/flower-power/node_modules/noble
node-gyp rebuild

make: Entering directory '/root/node_modules/flower-power/node_modules/noble/build'
  CC(target) Release/obj.target/hci-ble/src/hci-ble.o
  LINK(target) Release/hci-ble
  CC(target) Release/obj.target/l2cap-ble/src/l2cap-ble.o
  CC(target) Release/obj.target/l2cap-ble/src/utility.o
  LINK(target) Release/l2cap-ble
make: Leaving directory '/root/node_modules/flower-power/node_modules/noble/build'
flower-power@0.2.1 node_modules/flower-power
├── noble-device@0.1.3
└── noble@0.3.14 (debug@0.7.4, bplist-parser@0.0.6)

**To be honest, I am not sure what went wrong as this is my first nodejs script I want to run.**
**As last thing I had to install nodejs 'async' module**

*root@raspbmc:~/node_modules/flower-power# node test.js *
module.js:338
    throw err;
          ^
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/node_modules/flower-power/test.js:1:75)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

*root@raspbmc:~/node_modules/flower-power# npm install async*
async@1.3.0 node_modules/async

*root@raspbmc:~/node_modules/flower-power# node test.js*
connectAndSetup
readSystemId
	system id = 90:03:b7:00:00:c7:64:d1
readSerialNumber
	serial number = PI040298AA3J016997��Flower p
readFirmwareRevision
	firmware revision = 2014-06-23_hawaii-1.1.0_hardware-config-MP
readHardwareRevision
	hardware revision = 2013-07-26_hawaiiProduction-1.2_protoDV-bootloader
readManufacturerName
	manufacturer name = Parrot
readBatteryLevel
battery level = 75
readFriendlyName
	friendly name = Flower power 64D1���
writeFriendlyName
readColor
	color = green
readSunlight
sunlight = 4.67 mol/m²/d
readSoilElectricalConductivity
soil electrical conductivity = 153.00
readSoilTemperature
soil temperature = 26.73°C
readAirTemperature
air temperature = 28.76°C
readSoilMoisture
soil moisture = 14.97%
readCalibratedSoilMoisture
calibrated soil moisture = 16.90%
readCalibratedAirTemperature
calibrated air temperature = 29.70°C
readCalibratedSunlight
calibrated sunlight = 5.24 mol/m²/d
readCalibratedEa
calibrated EA = 9.03
readCalibratedEcb
calibrated ECB = 0.02 dS/m
readCalibratedEcPorous
calibrated EC porous = 0.44 dS/m
enableLiveMode
live mode
sunlight = 10.97 mol/m²/d
soil electrical conductivity = 154.00
soil temperature = 26.68°C
air temperature = 29.34°C
soil moisture = 15.10%
sunlight = 10.99 mol/m²/d
soil electrical conductivity = 154.00
soil temperature = 26.68°C
air temperature = 29.34°C
soil moisture = 15.10%
sunlight = 10.95 mol/m²/d
soil electrical conductivity = 154.00
soil temperature = 26.73°C
air temperature = 29.34°C
soil moisture = 15.10%
sunlight = 10.99 mol/m²/d
soil electrical conductivity = 153.00
soil temperature = 26.68°C
air temperature = 29.34°C
soil moisture = 14.72%
sunlight = 11.02 mol/m²/d
soil electrical conductivity = 154.00
soil temperature = 26.73°C
air temperature = 29.34°C
soil moisture = 14.97%
disableLiveMode
enableCalibratedLiveMode
calibrated live mode
calibrated soil moisture = 16.90%
calibrated air temperature = 30.28°C
calibrated sunlight = 12.41 mol/m²/d
calibrated EA = 9.03
calibrated ECB = 0.02 dS/m
calibrated EC porous = 0.44 dS/m
calibrated soil moisture = 16.65%
calibrated air temperature = 30.28°C
calibrated sunlight = 12.43 mol/m²/d
calibrated EA = 8.91
calibrated ECB = 0.02 dS/m
calibrated EC porous = 0.46 dS/m
calibrated soil moisture = 16.90%
calibrated air temperature = 30.28°C
calibrated sunlight = 12.44 mol/m²/d
calibrated EA = 9.03
calibrated ECB = 0.02 dS/m
calibrated EC porous = 0.44 dS/m
calibrated soil moisture = 16.77%
calibrated air temperature = 30.28°C
calibrated sunlight = 12.41 mol/m²/d
calibrated EA = 8.97
calibrated ECB = 0.02 dS/m
calibrated EC porous = 0.45 dS/m
calibrated soil moisture = 16.77%
calibrated air temperature = 30.32°C
calibrated sunlight = 12.48 mol/m²/d
calibrated EA = 8.97
calibrated ECB = 0.02 dS/m
disableCalibratedLiveMode
calibrated EC porous = 0.45 dS/m
ledPulse
delay
ledOff
disconnect
disconnected!

**Great work!**
**But I think it would be nice to inform about the dependencies**
**Or did I do something wrong?**

**Comment by sandeepmistry** [comment]
@Netfreak25 noble requires Node.js version 0.8 or greater, see [package.json](https://github.com/sandeepmistry/noble/blob/master/package.json#L22), you were initially trying to use it with 0.6.x  and npm 1.1.4 which are fairly old. Also, I would either recommend you switch to 0.10.x or 0.12.x, as the odd releases, 0.11.x are "unstable".

Please submit a pull request to add what you think is required to the read me, etc.

As for your issue with ```async``` and ```node-flower-power```, it is listed as a ```devDependency``` in ```package.json``` so will not be installed when to run ```npm install```. See: https://github.com/sandeepmistry/node-flower-power/blob/master/package.json#L26
