### ISSUE TITLE
Feature request: handle multiple bluetooth dongles from noble

### ISSUE THREAD

**Issue by yasdfgr** [sandeepmistry/noble#218]
I request the feature that noble can handle more than one bluetooth dongles in a system. This would be very helpfull for BLE mass applications, where the count of devices exceeds the maximum possible connections per dongle.

**Comment by sandeepmistry** [comment]
This can sort of be done now with multiple processes on Linux by setting an environment variable for each node process:

```sh
sudo NOBLE_HCI_DEVICE_ID=1 node <your file>.js
```

**Comment by sandeepmistry** [comment]
Closing this enhancement request until there is more demand.

**Comment by NAllred91** [comment]
I'm interested in this as well.  Multiple node process in a linux environment may be a decent solution though

**Comment by marukqs** [comment]
Would be great feature. In my case there are 20 kids in a class using microbits, however CSR chipset on teachers BLE->internet gateway has 5 connections limit. Thank you Sandeep for your great job!

**Comment by anant3110** [comment]
Can we have multiple node processes with different environment variables on Windows as well?

**Comment by shwetankshrey** [comment]
Can we have multiple processes on Windows with different environment variables as well?
