### ISSUE TITLE
The writeWithoutResponse on AlertLevel (1802) does not trigger anything on my pebblebee

### ISSUE THREAD

**Issue by npenin** [sandeepmistry/noble#220]
The writeWithoutResponse on AlertLevel (1802) does not trigger anything on my pebblebee nor my callback gets called whereas AlertLevel claims to support writeWithoutResponse.

This does not work
```js
matchingCharac[0].write(data, false, function(error){
                                                debug('callback');
                                                debug(error);
                                            });
```

But this does.
```js
matchingCharac[0].write(data, true, function(error){
                                                debug('callback');
                                                debug(error);
                                            });
```

Is this an issue in the documentation or somewhere else ? https://github.com/sandeepmistry/noble/wiki/Getting-started#writing-a-characteristic

**Comment by sandeepmistry** [comment]
@npenin it is a documentation issue, I've updated the getting started guide.

**Comment by npenin** [comment]
Thank you very much for the udpate
