### ISSUE TITLE
Add peripheral.connectable property

### ISSUE THREAD

**Issue by carlst** [sandeepmistry/noble#227]
Could the LE Advertising Report `Event_Type` be passed up to the `discover` handler?

This is useful for deciding whether or not to attempt a connection (e.g. a Beacon is non-connectable).

**Comment by sandeepmistry** [comment]
@carlst would something like a ```peripheral.connectable``` property work? It would be set to ``true`` or ``false`` ...

**Comment by carlst** [comment]
Yes, but for future expansion, it may also be helpful to retain other `Event_Type` information (undirected/directed, scannable).

I modified the pre-1.1.0 version for testing; `node-bluetooth-hci-socket` is a really nice addition, and will presumably make this change much cleaner.

**Comment by sandeepmistry** [comment]
Let's stick to ```.connectable``` for now, as OS X (10.10) provides this flag on discovery as well.

**Comment by sandeepmistry** [comment]
FYI, WIP for this can be found here: https://github.com/sandeepmistry/noble/tree/peripheral.connectable

Only Linux, Windows, and OS X 10.10 or above will have the property set to true or false ...

**Comment by sandeepmistry** [comment]
```peripheral.connectable``` branch has been merged into master, so this feature will be in the next release ...
