### ISSUE TITLE
Could not start scanning, state is unknown (not poweredOn)

### ISSUE THREAD

**Issue by TorstenRobitzki** [sandeepmistry/noble#228]
Hello,
I've tried to scan for BLE devices:

    noble = require('noble')

    noble.startScanning();
    console.log "Scanning"

this results in a error message (?):

    noble: Could not start scanning, state is unknown (not poweredOn)
    Scanning

Is the code wrong or is the message wrong? Is intended, that a message is printed on the screen? Shouldn't an exception being thrown if a precondition is not met?

I've tried 1.1.0 on OS/X 10.10

Cheers,
Torsten

**Comment by carlst** [comment]
@TorstenRobitzki: you might try waiting for the state to become `poweredOn`:

`noble.on('stateChange', function(state) {
  if (state === 'poweredOn')
    noble.startScanning();
  else
    noble.stopScanning();
});`

**Comment by TorstenRobitzki** [comment]
@carlst that works for me. Thank you! Is it intended to work this way? I mean I didn't plunged in or removed an BLE adapter.

**Comment by carlst** [comment]
@TorstenRobitzki: Yes, that is per `noble` spec. Perhaps needed to wait until any BLE device initialization or setup done by `noble` has finished, and the BLE device is ready for scanning to be initiated.

You might take a look at some of the examples, such as `examples/peripheral-explorer.js`

They are useful to better understand the control flow (scanning, connecting, discovering Services, discovering Characteristics, and so on).

**Comment by TorstenRobitzki** [comment]
@carlst Ok, thank you for the details.

**Comment by sandeepmistry** [comment]
@TorstenRobitzki do you still think an exception should be thrown? Happy to put that change in.

@carlst thanks for helping out!

**Comment by TorstenRobitzki** [comment]
Hi @sandeepmistry,
if I've misused the API and the API is able to detect this misuse, I think an exception would be appropriate. It's harder to ignore but it would change the API and thus could break existing code.

**Comment by sandeepmistry** [comment]
Done in https://github.com/sandeepmistry/noble/commit/dd152fd3901470140ed854b4d96add5e303d58c7

**Comment by TorstenRobitzki** [comment]
@sandeepmistry wow, that was fast ;-)

**Comment by quique123** [comment]
Im trying to read a ble char from a ble relay board from my rpi3.  startScanning() simply hangs or returns error that ble device isnt powered on.  Why is that?  

I know the ble on the rpi3 works because I use it to write to the relay board every so often and it works fine.
