### ISSUE TITLE
Setting Connect-Interval and Slave-Latency from Noble.

### ISSUE THREAD

**Issue by foldedtoad** [sandeepmistry/noble#237]
I am looking for a way to update the connect-intervals (min & max), and slave-latency from Noble.
The Bluez tool, hcitool, supports this operation with the following format --

    sudo hcitool lecup <handle> <min> <max> <latency> <timeout>

This will be used on a Raspberry-Pi for M2M type operations, where long connect-intervals are desired in order to extend battery life on peripheral devices.
While the peripheral can "suggest" these parameters, the central determines the final values to be used.
If the peripheral can't operate with the central's values, then the peripheral must quit the connection.

Is there any sample code showing how these parameters can be set?

**Comment by sandeepmistry** [comment]
@foldedtoad no API for this currently.

There was some discussion in #83, but the consensus then was to not have an API for this ...
