### ISSUE TITLE
Discover rate

### ISSUE THREAD

**Issue by Lock-up** [sandeepmistry/noble#246]
Hi,

im using bleacon on a Raspberry Pi with following code:

    var Bleacon = require('bleacon');
    var uuid = 'e2c56db5dffb48d2b060d0f5a71096e0';
    var major = 0; // 0 - 65535
    var minor = 0; // 0 - 65535
    var measuredPower = -59; // -128 - 127 (measured RSSI at 1 meter)
    Bleacon.startAdvertising(uuid, major, minor, measuredPower);

And on my MacBook (Yosemite 10.10.5) following code to discover the beacon:

    var noble = require('noble');
    noble.on('discover', function(peripheral) {
      var d = new Date();
      console.log(d.toLocaleString() + '.' + d.getMilliseconds() + ' Found peripheral');
    });
    noble.startScanning([], true);

I expected to get a log about every 100ms, but I get 3-4 logs every 2-3 seconds.

Whats wrong here ?

Greetings Jan

**Comment by sandeepmistry** [comment]
@Lock-up nothing can really be done for this unfortunately. The OS X CoreBluetooth framework / blued doesn't pass on all advertisement events.

This was also discussed in https://github.com/sandeepmistry/noble/issues/138
