### ISSUE TITLE
Help loging into beacon

### ISSUE THREAD

**Issue by dorshay6** [sandeepmistry/noble#247]
Hi

My beaons works well with the app that suplied by the factory (lightBlue app on ios), the beacons requiers my to login by writing '0xAA140611' to characteristic 7.

I cant write this value to the beacon and cange his other characteristics.

Any help?

        noble.on('discover', function(peripheral)
        {
            console.log('Found device with local name: ',peripheral.uuid.toString('utf8'));
            //return;
            peripheral.connect(function(error)
            {
                //console.log('connected to peripheral: ' + peripheral.uuid);
                peripheral.discoverServices([], function(error, services)
                {
                    if(!services[2])
                        return;

                    var deviceInformationService = services[2];
                    //console.log('discovered device information service',services[2]);

                    deviceInformationService.discoverCharacteristics(['FFF7','FFF5'], function(error, characteristics)
                    {
                        //console.log('discovered the following characteristics:',characteristics);
                        console.log(' CHAR ',characteristics.length)

                        if(!characteristics[0])
                        {
                            return;
                        }
                        characteristics[0].read(function(error, data)
                        {
                            // data is a buffer
                            console.log('bps: ' + data,error);
                            characteristics[0].write(new Buffer([0xAA140611]), false, function(x,y)
                            {
                                console.log(x,y)
                                characteristics[1].write(new Buffer(['dor shay']), true, function(error)
                                {
                                    peripheral.disconnect(function(error) {
                                       console.log('disconnected from peripheral: ' + peripheral.uuid);
                                    });
                                })
                            });
                        });

                        return;
                    });
                });
            });
        });

**Comment by sandeepmistry** [comment]
@dorshay6 please take a look at the Node.js Buffer API docs: https://nodejs.org/api/buffer.html

The buffer you are trying to write doesn't result in the value you expect:

```sh
$ node
> new Buffer([0xAA140611])
<Buffer 11>
> new Buffer('AA140611', 'hex')
<Buffer aa 14 06 11>
> new Buffer([0xaa, 0x14, 0x06, 0x11])
<Buffer aa 14 06 11>
```

I believe you want to use one of the later options. I'll close this for now, but re-open if my suggestion doesn't resolve the issue.
