### ISSUE TITLE
Error installing noble (win10, Node 4.1.1)

### ISSUE THREAD

**Issue by AlexDmr** [sandeepmistry/noble#252]
Got A LOT of errors, I'm experienced with NodeJS and gyp. I suppose that for now either win10 or Node 4 is not yet supported ?

**Comment by sandeepmistry** [comment]
@AlexDmr see https://github.com/sandeepmistry/node-bluetooth-hci-socket/issues/7. We need node-usb to support Node.js 4.x ...

**Comment by sandeepmistry** [comment]
https://github.com/sandeepmistry/node-bluetooth-hci-socket/issues/7 has been resolved. Please try installing again.
