### ISSUE TITLE
noble stateChange not auto poweredOn when inject USB bluetooth!

### ISSUE THREAD

**Issue by tinamore** [sandeepmistry/noble#262]
Hi
I have a problem. When running example enter-exit.js:

noble.on('stateChange', function(state) {
  if (state === 'poweredOn') {
  console.log(noble);
  console.log('start');
    noble.startScanning([], true);
  } else {
	console.log('STOP');
    noble.stopScanning();
  }
});

1. if reject USB bluetooth then noble stateChange fire noble.stopScanning() is good.
2. But when i inject USB again then NoBle not Fire poweredOn, so "noble.startScanning([], true);" not run again.

Can anyone help me fix problem.

**Comment by sandeepmistry** [comment]
@tinamore noble does not have support to power up the adapter.

After inserting your USB adapter you can run: ```sudo hciconfig hci0 up``` to power it up.
