### ISSUE TITLE
Write characteristics help

### ISSUE THREAD

**Issue by dneykov** [sandeepmistry/noble#263]
I'm implementing central client with noble on raspberry pi and iOS app for peripherals.
My problem is that when it try to write characteristics on peripheral service delegate method didUpdateValueForCharacteristic is not called so I can't receive the value on the app

Thanks.

**Comment by sandeepmistry** [comment]
@dneykov please see the CoreBluetooth documentation, the ```didUpdateValueForCharacteristic``` delegate is only used for notifications.

You want to use ```
peripheralManager:didReceiveWriteRequests:```: https://developer.apple.com/library/ios/documentation/CoreBluetooth/Reference/CBPeripheralManagerDelegate_Protocol/index.html#//apple_ref/occ/intfm/CBPeripheralManagerDelegate/peripheralManager:didReceiveWriteRequests:
