### ISSUE TITLE
Can prevent clone iBeacon via detect unique with Mac Address ?

### ISSUE THREAD

**Issue by tinamore** [sandeepmistry/noble#271]
Hi.

I plan to use ibeacon for RFID tag active.

But, I known that user can use a App on Android with name "Android iBeacon Locate" for clone a real ibeacon into a virtual Ibeacon with  same UUID, major, minor or identifier...Link: http://stackoverflow.com/questions/23383606/how-to-prevent-cloning-in-ibeacons-and-avoid-conflicts-among-beacons

I see in the structure of "Peripheral discovered" have Mac Address:
```
address: "<BT address">, // Bluetooth Address of device
```
I wonder that can use the Mac Address to detect unique? Can a normal user (NOT a technology expert, Because I think everything can be faked by an expert) Clone Mac Address ibeacon ?

**Comment by sandeepmistry** [comment]
Yes, the BT address can be cloned, maybe not by a non-tech expert, but it is possible for a tech expert.

If you are concerned about this, I would reconsider using Bluetooth for your application.
