### ISSUE TITLE
Reading Major and minor of a BLE device

### ISSUE THREAD

**Issue by karthikbnd** [sandeepmistry/noble#280]
Hello
I am able to run the noble and get the mac address, but i want to get the UUID, Major and Minor of a BLE(Beacon) device. How can i get that?

**Comment by sandeepmistry** [comment]
@karthikbnd please see the following library: https://github.com/sandeepmistry/node-bleacon

**Comment by karthikbnd** [comment]
Hai
I want a test program to scan a beacon and console log the Major, minor and
rssi.
Can you please provide it.
I did the following but its at scanning
var Bleacon = require('bleacon');

//Bleacon.startScanning([uuid], [major], [minor]);// scan for bleacons with
a particular uuid. major, and minor
Bleacon.startScanning([]); // scan for any bleacons
console.log('Started Scanning........');
Bleacon.on('discover', function(bleacon) {
    console.log('beacon found: ' + JSON.stringify(bleacon));
    var uuid = bleacon.uuid;
    var major = bleacon.major;
    var minor = bleacon.minor;
    var date = new Date();
    console.log('Found BLE:', 'UUID:',uuid, ' Major:',major,'Minor:',minor,
'Date:',date );
    //var measuredPower = manufacturerData.readInt8(24);
});

Bleacon.stopScanning();


output is
y@hubblue:~/node_modules$ node filescan_beacon.js
Started Scanning........


On Sat, Dec 5, 2015 at 4:05 PM, Sandeep Mistry <notifications@github.com>
wrote:

> Closed #280 <https://github.com/sandeepmistry/noble/issues/280>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sandeepmistry/noble/issues/280#event-483446294>.
>



-- 
Regards
Karthik BANDI

**Comment by sandeepmistry** [comment]
@karthikbnd you will need to run with ```sudo``` or run as root.

Alternatively you can following these instructions: https://github.com/sandeepmistry/noble#running-without-rootsudo

**Comment by karthikbnd** [comment]
Hai
I want to scan for every 10sec and get the data, can i get help in setting
the interval

On Tue, Dec 8, 2015 at 2:02 AM, Sandeep Mistry <notifications@github.com>
wrote:

> @karthikbnd <https://github.com/karthikbnd> you will need to run with sudo
> or run as root.
>
> Alternatively you can following these instructions:
> https://github.com/sandeepmistry/noble#running-without-rootsudo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sandeepmistry/noble/issues/280#issuecomment-162720172>
> .
>



-- 
Regards
Karthik BANDI

**Comment by cyclonmaster** [comment]
I follow the node-bleacon same as karthik did, also get nothing from estimote:

pi@raspberrypi:~/Downloads $ sudo node bleaconscan.js
Started Scanning........

Do I need to configure anything?

**Comment by karthikbnd** [comment]
Hallo,

ich habe gerade die Petition „sushma swaraj : Long term visa for dependant
parents of Indians in Germany" unterschrieben und wollte dich fragen, ob du
auch mitmachst.

Unser Ziel ist es, 781 Unterschriften zu sammeln und dafür brauchen wir
Unterstützung. Hier kannst du mehr über die Petition erfahren:

http://chng.it/dZfpvd2XhV

Vielen Dank!
Karthik
