### ISSUE TITLE
How to extract a "compiled executable file" out of NOBLE?

### ISSUE THREAD

**Issue by boredSinan** [sandeepmistry/noble#281]
A few weeks ago I started with noble and implemented an indoor tracking system for BLE Beacons.

Now I wanna install this implementation on all available Windows computers, there are about 20. 
But I don't wanna go through the whole installation guide for each computer as listed here:
https://github.com/sandeepmistry/noble#windows

Are there any possibilities to extract a "compiled executable file" out of the whole NOBLE system which consists of:
(Python2.7 + Node.js + node-gyp + hci-socket + VS2013 + noble + Own_JavaScript_Implementation)? 

So the indoor tracking system would be portable and easy to install on all available computers! 
Installing all the above mentioned software on each computer would be terrible! 
So I only need 1 computer for implementation and development. The others should run the "compiled executable file"!

Thanks for your reply ;)

**Comment by sandeepmistry** [comment]
Follow up discussion here: https://github.com/sandeepmistry/noble/issues/282
