### ISSUE TITLE
Typo in lib/hci-socket/hci.js (masterClockAccuracy)

### ISSUE THREAD

**Issue by carlst** [sandeepmistry/noble#284]
In `lib/hci-socket/hci.js Hci.prototype.processLeConnComplete` (around line 491) should:
` var masterClockAccuracy = data.readUInt8(15); // TODO: multiplier?`
be:
` var masterClockAccuracy = data.readUInt8(16); // TODO: multiplier?`

**Comment by sandeepmistry** [comment]
@carlst thanks for letting me know, corrected in https://github.com/sandeepmistry/noble/commit/b31d6d6cb1af5d7e3c127ed4597cd22543b77ff5.
