### ISSUE TITLE
The Thing System claims that BlueZ requires 4.100 and 4.100

### ISSUE THREAD

**Issue by RussNelson** [sandeepmistry/noble#286]
Quoting from http://thethingsystem.com/dev/Bootstrapping-the-Raspberry-Pi.html :

The noble library library is tested with BlueZ 4.100 and 4.101.

Is this still true?

**Comment by sandeepmistry** [comment]
@RussNelson good question, there's no need to build BlueZ from source when using the latest version of noble. I would recommend using whatever version of BlueZ that is available with the OS'es distribution/package manger.
