### ISSUE TITLE
Read data to not discovered BLE service with .discoverServices

### ISSUE THREAD

**Issue by Shibonja** [sandeepmistry/noble#289]
Hi guy's

Is there any way that I can read an characteristic from a service that is not discovered before with discoverSomeServicesAndCharacteristics().

I am using noble with bluez 4.101 to connect with HM10 ble module which is in iBeacon mode.

**Comment by sandeepmistry** [comment]
@Shibonja if you know the handles before hand, try the following read/write handle API's: https://github.com/sandeepmistry/noble#handle

Note: the preferred approach is still to discover services and characteristics, the handle API's do not work well on OS X.

**Comment by Shibonja** [comment]
HI @sandeepmistry 

Thanks for fast answer, the handles are know before.

**Comment by sandeepmistry** [comment]
@Shibonja great!
