### ISSUE TITLE
Write to Characteristics without Pairing?

### ISSUE THREAD

**Issue by antonkluev** [sandeepmistry/noble#307]
Guys, ive heard, that it is possible to talk to BLE without pairing. Is it true and is it possible with noble?
thx!

**Comment by sandeepmistry** [comment]
@antonkluev depends on the BLE peripheral (device), however most devices do not require pairing, so noble will work with these.

**Comment by antonkluev** [comment]
thanks for reply! how can i write to the known characteristic directly without connecting in noble? can you help me please? :)

**Comment by antonkluev** [comment]
is actually connecting = pairing?

**Comment by sandeepmistry** [comment]
@antonkluev please seeing the examples folder or the wiki.

* https://github.com/sandeepmistry/noble/tree/master/examples
* https://github.com/sandeepmistry/noble/wiki/Getting-started
