### ISSUE TITLE
Make noble work with JXCore

### ISSUE THREAD

**Issue by marcnicholas** [sandeepmistry/noble#308]
I guess asking JXCore's "100% compatible with node" guarantee to extend to bindings is a bit much :)

Currently getting this:
```
dyld: lazy symbol binding failed: Symbol not found: __ZN4node6Buffer3NewEPKcm
  Referenced from: /Users/marc/Code/noble/node_modules/xpc-connection/build/Release/binding.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN4node6Buffer3NewEPKcm
  Referenced from: /Users/marc/Code/noble/node_modules/xpc-connection/build/Release/binding.node
  Expected in: dynamic lookup

Trace/BPT trap: 5
```

I guess the version of node to bind to gets set in the gyp build process somewhere?

EDIT: this is on a Mac....haven't tried Linux yet.

**Comment by sandeepmistry** [comment]
> I guess the version of node to bind to gets set in the gyp build process somewhere?

Good question! For regular node you can pass a target parameter in: http://stackoverflow.com/a/15983893/2020087 (I have no idea what JXCore would need).

It feels like the build parameters are not right, for example it might be using Node.js headers but linking to JXCore? 

node-xpc-connection uses [```nan```](https://github.com/nodejs/nan) now, so doesn't use the the Node.js Buffer API's directly, but I imagine this line does something with Buffer new:

https://github.com/sandeepmistry/node-xpc-connection/blob/master/src/XpcConnection.cpp#L186

Maybe comment it out and rebuild to see if it's the root cause :) (as well as any other ```Nan::CopyBuffer``` lines you see ?

**Comment by marcnicholas** [comment]
I edited the gyp config and got it to properly use jx (I think). But now seem to get some weird include errors...

```Marcs-MacBook-Pro:build marc$ make
  CXX(target) Release/obj.target/binding/src/XpcConnection.o
In file included from ../src/XpcConnection.cpp:5:
In file included from /Users/marc/.node-gyp/jxb310/src/node_buffer.h:8:
In file included from /Users/marc/.node-gyp/jxb310/src/jx/commons.h:34:
In file included from /Users/marc/.node-gyp/jxb310/src/jx/btree_map.h:31:
/Users/marc/.node-gyp/jxb310/src/jx/btree.h:919:10: warning: class 'btree_internal_locate_plain_compare' was previously declared as a struct
      [-Wmismatched-tags]
  friend class btree_internal_locate_plain_compare;
         ^
/Users/marc/.node-gyp/jxb310/src/jx/btree.h:893:8: note: previous use is here
struct btree_internal_locate_plain_compare {
       ^
/Users/marc/.node-gyp/jxb310/src/jx/btree.h:919:10: note: did you mean struct here?
  friend class btree_internal_locate_plain_compare;
         ^~~~~
         struct
/Users/marc/.node-gyp/jxb310/src/jx/btree.h:1188:8: error: expected member name or ';' after declaration specifiers
  void verify() const;
  ~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/AssertMacros.h:1339:29: note: expanded
      from macro 'verify'
                #define verify(assertion) __Verify(assertion)
                                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/AssertMacros.h:420:5: note: expanded
      from macro '__Verify'
                  do                                                                      \
                  ^
In file included from ../src/XpcConnection.cpp:5:
In file included from /Users/marc/.node-gyp/jxb310/src/node_buffer.h:8:
In file included from /Users/marc/.node-gyp/jxb310/src/jx/commons.h:34:
In file included from /Users/marc/.node-gyp/jxb310/src/jx/btree_map.h:31:
/Users/marc/.node-gyp/jxb310/src/jx/btree.h:2049:16: error: expected unqualified-id
void btree<P>::verify() const {
               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/AssertMacros.h:1339:29: note: expanded
      from macro 'verify'
                #define verify(assertion) __Verify(assertion)
                                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/AssertMacros.h:420:5: note: expanded
      from macro '__Verify'
                  do                                                                      \
                  ^
In file included from ../src/XpcConnection.cpp:5:
In file included from /Users/marc/.node-gyp/jxb310/src/node_buffer.h:8:
In file included from /Users/marc/.node-gyp/jxb310/src/jx/commons.h:34:
In file included from /Users/marc/.node-gyp/jxb310/src/jx/btree_map.h:32:

**Comment by marcnicholas** [comment]
Couple of updates:

(1) Works fine on Linux with the HCI interface (good).
(2) The JX team figured out a [workaround](https://github.com/jxcore/jxcore/issues/802#issuecomment-175637609)

**Comment by sandeepmistry** [comment]
@marcnicholas awesome news! Great to hear noble and it's dependencies work as is :)

You have it working on a MIPS board?

**Comment by marcnicholas** [comment]
I have to setup a cross-compile gyp environment and possibly an OpenWRT package to get it to MIPS...but that's the plan.

**Comment by sandeepmistry** [comment]
Cool, keep me posted.

Just a heads up there might be some issues with the endianness of the socket filter mask on MIPS, but I haven't confirmed it (https://github.com/sandeepmistry/noble/issues/294).

**Comment by marcnicholas** [comment]
I've had it running on our MIPS board for a while under node.js. Broadcast works fine, but I've never been able to get a Peripheral mode connection established -- even with the native Bluez tools.

**Comment by TheMaverickProgrammer** [comment]
where did you get the folder `~/.node-gyp/jxb310`? I've compiled jxcore from source. Have same issues as you did with Noble.
