### ISSUE TITLE
replace peripheralUuid with peripheralId in the bindings?

### ISSUE THREAD

**Issue by jrobeson** [sandeepmistry/noble#311]
I see that peripheralUuid got replaced in the "public" interfaces in https://github.com/sandeepmistry/noble/commit/0ff0ba66186e63e35de6798e39278d185d46f200 . is there any reason that change isn't propagated throughout the bindings?

**Comment by sandeepmistry** [comment]
Agreed, this is something that needs to get done for consistency ....

**Comment by jrobeson** [comment]
closing then, since the work is (mostly) done in https://github.com/sandeepmistry/noble/pull/316
