### ISSUE TITLE
Can I skip encription procedure for TK and STK?

### ISSUE THREAD

**Issue by BYAKheee** [sandeepmistry/noble#333]
bleno/noble are awesome library. I’ｍ using it on Rasberry Pi. I have a concern.

Central and peripheral disconnect after exchange LTK and establish pairing.
Then re-connect them, they will exchange TK and STK again.
Can I skip encription procedure for TK and STK?

**Comment by sandeepmistry** [comment]
@BYAKheee there is no persistent key mechanism in noble at this time.

TK and STK will only be exchanged if a "secure" characteristic is read. Can you please confirm your peripheral has a secure characteristic and you are trying to access it?

**Comment by BYAKheee** [comment]
Thanks response!

OK, I got stable connection by another way.
I think bleno/noble's SMP conflict with kernel SMP smoetimes.
