### ISSUE TITLE
Parsing Company Identifier

### ISSUE THREAD

**Issue by brghena** [sandeepmistry/noble#334]
Is there any reason noble doesn't automatically parse the Company ID field within Manufacturer Specific Data?

Per the BLE CSSv6, Company ID should be the first two bytes of the Manufacturer Specific Data field (exactly the same as 16-bit UUIDs in Service Data fields). Nominally, it would be good to match the service data format, but with backwards compatibility issues, it might instead be best to add something along the lines of `advertisement.companyId`. You would have to keep those first two bytes within the `advertisement.manufacturerData` buffer or break old code.

One possible problem would be devices that do not follow the specification. I know Flower Power does not transmit a Company ID in the Manufacturer Specific Data field.

I'm happy to write a pull request if you think it's something you might want included in Noble.

**Comment by sandeepmistry** [comment]
> Is there any reason noble doesn't automatically parse the Company ID field within Manufacturer Specific Data?

noble is based on the OS X and iOS CoreBluetooth API. Which does not parse the manufacturer data company id out.

I prefer to leave it as is, it makes it easier to deal with devices like the Flower Power which do not following the specification.
