### ISSUE TITLE
"Discover All Primary Services" vs "Discover Primary Service by Service UUID"

### ISSUE THREAD

**Issue by TorstenRobitzki** [sandeepmistry/noble#335]
Hello,
I'm using noble to test a new GATT service implementation. In one of the test cases, the GATT server has to be tested with both of the specified GATT Primary Service Discovery sub-procedures. I thought (or better wished), when I use `peripheral.discoverServices()` without a list of UUIDs, the Discover All Primary Services sub-procedure would be executed and when I call that function with a list of UUIDs, that Discover Primary Service by Service UUID would be used. But it is not like this, even when my UUID list contains only one element.

Does some of you have an idea how I could force the Mac (yosemite) implementation to use Discover Primary Service by Service UUID? Are there others who like to define exactly, what GATT sub-procedures are executed?

Cheers,
Torsten

**Comment by sandeepmistry** [comment]
@TorstenRobitzki 

> Does some of you have an idea how I could force the Mac (yosemite) implementation to use Discover Primary Service by Service UUID? Are there others who like to define exactly, what GATT sub-procedures are executed?

I don't know how to do this unfortunately. It doesn't look like CoreBluetooth/blued on OS X supports this.
