### ISSUE TITLE
Service discovery with 128-bit UUIDs doesn't seem to work

### ISSUE THREAD

**Issue by billsalt** [sandeepmistry/noble#344]
I'm a NOOB, so it could well be that the issue is mine, but...  I have a device with a custom 128-bit UUID and want to discover it.  The code below discovers all devices in range, not just mine (eNote).  Is this an issue for noble?  Perhaps my UUID formatting is incorrect?

var noble = require('noble');
var serviceUUIDs =

noble.on('stateChange', function(state) {
  if (state === 'poweredOn') {
    noble.startScanning();
  } else {
    noble.stopScanning();
  }
});

noble.on('discover', function(peripheral) {
  peripheral.connect(function(error) {
    console.log('connected to service discovery peripheral: ' + peripheral.uuid);
    peripheral.discoverServices(['BBC21523008EFE6B28EED6A44F9CB5DA'], function(error, services) {
      console.log('service discovery local name is:');
      console.log('\t\t' + peripheral.advertisement.localName);
    });
  });
});

**Comment by sandeepmistry** [comment]
@billsalt it sounds like you want to add a UUID scan filter, but are not passing any arguments into ```noble.startScanning()```. Please see:

 * https://github.com/sandeepmistry/noble#start-scanning
 * https://github.com/sandeepmistry/noble/blob/master/examples/pizza/central.js#L18
