### ISSUE TITLE
Observation: characteristic UUID's are case sensitive

### ISSUE THREAD

**Issue by billsalt** [sandeepmistry/noble#349]
Expected that after scanning for service using all uppercase that the characteristic comparisons would also work as upper case, but the comparison is case sensitive.  Code construct is for my eNote device.  The commented var definitions fail, but the lower case ones work correctly:

var noble = require('noble');

var eNoteServiceUuid = 'BBC21523008EFE6B28EED6A44F9CB5DA';
//var eNoteLEDCharacteristicUuid = 'BBC21525008EFE6B28EED6A44F9CB5DA';
var eNoteLEDCharacteristicUuid = 'bbc21525008efe6b28eed6a44f9cb5da';
//var eNoteBlockNumberCharacteristicUuid = 'BBC21526008EFE6B28EED6A44F9CB5DA';
var eNoteBlockNumberCharacteristicUuid = 'bbc21526008efe6b28eed6a44f9cb5da';
//var eNoteBlockDataCharacteristicUuid = 'BBC21527008EFE6B28EED6A44F9CB5DA';
var eNoteBlockDataCharacteristicUuid = 'bbc21527008efe6b28eed6a44f9cb5da';
//var eNoteCommandStatusCharacteristicUuid = 'BBC21528008EFE6B28EED6A44F9CB5DA';
var eNoteCommandStatusCharacteristicUuid = 'bbc21528008efe6b28eed6a44f9cb5da';

noble.on('stateChange', function(state) {
  if (state === 'poweredOn') {
    //
    // Once the BLE radio has been powered on, it is possible
    // to begin scanning for services. Pass an empty array to
    // scan for all services (uses more time and power).
    //
    console.log('scanning...');
    noble.startScanning([eNoteServiceUuid], false);
  }
  else {
    noble.stopScanning();
  }
})

var eNoteService = null;
var eNoteLEDCharacteristic = null;
var eNoteBlockNumberCharacteristic = null;
var eNoteBlockDataCharacteristic = null;
var eNoteCommandStatusCharacteristic = null;

noble.on('discover', function(peripheral) {
  // we found a peripheral, stop scanning
  noble.stopScanning();

  //
  // The advertisment data contains a name, power level (if available),
  // certain advertised service uuids, as well as manufacturer data,
  // which could be formatted as an iBeacon.
  //
  console.log('found peripheral:', peripheral.advertisement);
  //
  // Once the peripheral has been discovered, then connect to it.
  // It can also be constructed if the uuid is already known.
  ///
  peripheral.connect(function(err) {
    //
    // Once the peripheral has been connected, then discover the
    // services and characteristics of interest.
    //
    peripheral.discoverServices([eNoteServiceUuid], function(err, services) {
      services.forEach(function(service) {
        //
        // This must be the service we were looking for.
        //
        console.log('found service:', service.uuid);

        //
        // So, discover its characteristics.
        //
        service.discoverCharacteristics([], function(err, characteristics) {

          characteristics.forEach(function(characteristic) {
            //
            // Loop through each characteristic and match them to the
            // UUIDs that we know about.
            //
            console.log('found characteristic:', characteristic.uuid);

            if (eNoteLEDCharacteristicUuid == characteristic.uuid) {
              eNoteLEDCharacteristic = characteristic;
              console.log('found LED');
            }
            else if (eNoteBlockNumberCharacteristicUuid == characteristic.uuid) {
              eNoteBlockNumberCharacteristic = characteristic;
              console.log('found BlockNumber');
            }
            else if (eNoteBlockDataCharacteristicUuid == characteristic.uuid) {
              eNoteBlockDataCharacteristic = characteristic;
              console.log('found BlockData');
            }
            else if (eNoteCommandStatusCharacteristicUuid == characteristic.uuid) {
              eNoteCommandStatusCharacteristic = characteristic;
              console.log('found CommandStatus');
            }
          })

          //
          // Check to see if we found all of our characteristics.
          //
          if (eNoteLEDCharacteristic &&
              eNoteBlockDataCharacteristic &&
              eNoteBlockNumberCharacteristic &&
              eNoteCommandStatusCharacteristic) {
            //
            // We did, so bake a pizza!
            //
            console.log('eNote is all here!!!');
          }
          else {
            console.log('missing characteristics');
          }
        })
      })
    })
  })
})

**Comment by sandeepmistry** [comment]
@billsalt yep, this is a known limitation of noble, sort of related to #331.
