### ISSUE TITLE
Duplicate messages received from bluetooth device

### ISSUE THREAD

**Issue by mdlampi** [sandeepmistry/noble#350]
On Mac OS X 10.10.5 Yosemite we have observed that NOBLE sometimes returns duplicate or even triplicate messages.

The Mac Packet Logger program shows there should be only one message according to the timestamps of the data it logs as well as the timestamps logged by the NOBLE application.

Other than placing a higher level filter comparing previous input to the latest input, is there a fix for this?

**Comment by sandeepmistry** [comment]
@mdlampi please provide sample code and output.

**Comment by mdlampi** [comment]
@sandeepmistry Here is a log of the program output. Attached are the bluetooth routines that perform the reads via NOBLE, and Mac Packet Logger logs taken during the time the program was executed. There are 3 "Got duplicate" occurrences logged, along with the hex strings for the messages returned by NOBLE.

Let me know if you need any more information.

Thanks!

[Archive.zip](https://github.com/sandeepmistry/noble/files/172436/Archive.zip)

**Comment by sandeepmistry** [comment]
@mdlampi I don't think the zip file contains all the code.

Anyways, it would really speed things up if you provided a minimal way to reproduce the issue in pure javascript (no coffeescript).

**Comment by mdlampi** [comment]
@sandeepmistry We had a new team take a look at the bluetooth stack on the device. There were some situations where packets could be overwritten and this is what probably caused the duplicate messages.

Thank you anyway!
