### ISSUE TITLE
Crashing on "Attribute not found"

### ISSUE THREAD

**Issue by ayhoung** [sandeepmistry/noble#356]
I'm wondering if this HCI event is handled, as everytime there is this error:
2016-03-15 11:31:57.341809 > ACL data: handle 64 flags 0x02 dlen 9
    ATT: Error (0x01)
      Error: Attribute not found (10)
      Read By Type req (0x08) on handle 0x002b

Noble seems to stop responding.

**Comment by sandeepmistry** [comment]
@ayhoung please provide a minimal code example on how to reproduce the issue and full HCI dump capture.

**Comment by ayhoung** [comment]
sorry was planning on, but having trouble recreating this exact scenario, will try to provide when it happens again!

**Comment by sandeepmistry** [comment]
Ok, I'll close this issue for now, please re-open when you have more data.
