### ISSUE TITLE
Enhancement suggestion: optional callbacks for when noble has started/stopped scanning

### ISSUE THREAD

**Issue by ayhoung** [sandeepmistry/noble#361]
As the title suggests, there should to a callback for noble status update on when it stops scanning to increase performance of the bluetooth connection. Please correct me if I'm wrong on this, but it seems the connection integrity/speed benefits from noble stopping scanning.

Thus I would suggest adding callbacks for when noble has completely stopped/started scanning (noble.startScanning(), noble.stopScanning()), and then initiate a connection.

**Comment by sandeepmistry** [comment]
@ayhoung 

> Please correct me if I'm wrong on this, but it seems the connection integrity/speed benefits from noble stopping scanning.

Possibly, but I haven't investigated anything myself.

> Thus I would suggest adding callbacks for when noble has completely stopped/started scanning (noble.startScanning(), noble.stopScanning()), and then initiate a connection.

Please see:
 * https://github.com/sandeepmistry/noble#start-scanning
 * https://github.com/sandeepmistry/noble/blob/master/lib/noble.js#L112
 * https://github.com/sandeepmistry/noble#scan-started
 * https://github.com/sandeepmistry/noble#scan-stopped
