### ISSUE TITLE
Unable to install noble on Mac OSX El Capitan (MacBook Pro Retina 13")

### ISSUE THREAD

**Issue by ADenisUA** [sandeepmistry/noble#384]
Does noble lib is compatible with Mac OSX El Capitan (MacBook Pro Retina 13")?
I'm receiving:

Deniss-MacBook-Pro:~ davdeev$ sudo npm install noble
/Users/davdeev
├── noble@1.3.0 
└── sphero@0.9.2 

npm WARN optional Skipping failed optional dependency /noble/bluetooth-hci-socket:
npm WARN notsup Not compatible with your operating system or architecture: bluetooth-hci-socket@0.4.4
npm WARN enoent ENOENT: no such file or directory, open '/Users/davdeev/package.json'
npm WARN davdeev No description
npm WARN davdeev No repository field.
npm WARN davdeev No README data
npm WARN davdeev No license field.

Please help. Thanks

**Comment by sandeepmistry** [comment]
> Does noble lib is compatible with Mac OSX El Capitan (MacBook Pro Retina 13")?

@ADenisUA yes, it is compatible with Mac OSX El Capitan.

> npm WARN optional Skipping failed optional dependency /noble/bluetooth-hci-socket:
> npm WARN notsup Not compatible with your operating system or architecture: bluetooth-hci-socket@0.4.4

These dependencies are not needed on OS X, just ```xpc-connection```.
