### ISSUE TITLE
NOBLE_REPORT_ALL_HCI_EVENTS

### ISSUE THREAD

**Issue by jeberhardt** [sandeepmistry/noble#385]
Does using NOBLE_REPORT_ALL_HCI_EVENTS affect the speed and performance of the script at all? I am presuming that it is faster not to report all events, but I haven't really seen any comment or documentation on what it does.

Also, is the correct format to report the events:
        NOBLE_REPORT_ALL_HCI_EVENTS=1

... and to not report all events:
        NOBLE_REPORT_ALL_HCI_EVENTS=0

Just checking, I find the readme slightly confusing.

**Comment by sandeepmistry** [comment]
> Does using NOBLE_REPORT_ALL_HCI_EVENTS affect the speed and performance of the script at all? I am presuming that it is faster not to report all events, but I haven't really seen any comment or documentation on what it does.

It will take more CPU

> Also, is the correct format to report the events: NOBLE_REPORT_ALL_HCI_EVENTS=1

Yes

> ... and to not report all events: NOBLE_REPORT_ALL_HCI_EVENTS=0

default is off.

> Just checking, I find the readme slightly confusing.

I'm open to suggestions to clarify the readme. Pull requests welcome.
