### ISSUE TITLE
Update Rssi when connected

### ISSUE THREAD

**Issue by nicwsm** [sandeepmistry/noble#393]
Hi, I configured my BLE end device to continue broadcasting iBeacons packets even when it's connected to a central, however, the noble.on('discover') on the central side doesn't pick up the RSSI signals anymore once the central initiates a connection to the end device. Any explanation or solution how I can solve this?

Thanks!

**Comment by sandeepmistry** [comment]
@nicwsm if you are connected, I suggest using https://github.com/sandeepmistry/noble#update-rssi.
