### ISSUE TITLE
Bluetooth Pairing and Auto-Connect

### ISSUE THREAD

**Issue by Irrelon** [sandeepmistry/noble#396]
Hi ya, thank you for such a great library, it's very awesome!

I wondered if I might be able to ask a few questions as my knowledge of bluetooth is a bit limited and having spent a while with noble I'm trying to achieve something and could do with some help...

I am trying to create a system whereby a user can initiate a pairing to my Node.js server from their phone, after which whenever the phone is in range of the Node.js bluetooth USB dongle the Node.js server connects to the phone (phone in this case is an iPhone but it could be an android phone as well).

I know from using my car's audio bluetooth that my phone can "just connect" whenever I turn the car on. 

1) Can I simulate this kind of connection in Node.js so that whenever the front door opens (I have a sensor on the front door and my Node.js app knows it has opened), my Node.js server attempts to connect to all known devices it has been previously paired to? This would allow me to identify the person coming through the front door by the device they have in their pocket.

2) Is this something I should be trying from Noble or Bleno?

3) Is this something that is possible without installing an app on the phone? I can pair to my car audio via the iPhone's bluetooth menu without any other app installed, and the car can later connect without any app installed so I'm guessing it must be possible?

Really appreciate your effort on this library. You should set up a donation button with Flatr or PayPal. Developers like me don't mind donating to projects like this.

**Comment by sandeepmistry** [comment]
> 1) Can I simulate this kind of connection in Node.js so that whenever the front door opens (I have a sensor on the front door and my Node.js app knows it has opened), my Node.js server attempts to connect to all known devices it has been previously paired to? This would allow me to identify the person coming through the front door by the device they have in their pocket.

Mostly likely, pairing support is still "experimental" in both noble and bleno. It's only needed for secure characteristics.

> 2) Is this something I should be trying from Noble or Bleno?

Personally, I'd use bleno, then the smartphones could connect to it automatically. Keep in mind your car is probably using Bluetooth classic and not 4.0. Most of the smart locks on the market use Bluetooth 4.0 and act as a BLE peripheral.

> 3) Is this something that is possible without installing an app on the phone? I can pair to my car audio via the iPhone's bluetooth menu without any other app installed, and the car can later connect without any app installed so I'm guessing it must be possible?

See answer in 2, you'll most likely need an app on the phone.


PS: I've setup gitter.im for both noble and bleno, I'd prefer if that was used for discussions like topics as apposed to a Github for the future.
