### ISSUE TITLE
MTU is 50, I want it to be higher

### ISSUE THREAD

**Issue by peturh** [sandeepmistry/noble#400]
I have a Raspberry Pi 3 that I'm using for BLE connection to a TI CC2650. I wan't to send about 300 bytes of data to the device in total, and I want to increase the MTU. When I log the MTU size on both devices, it says 50. But I have no idea where I set this. 

On row 205 in `lib/hci-socket/bindings.js` in this project I can see that we try to set the MTU to 256.

`this._gatts[handle].exchangeMtu(256);`

In the file `gatt.js` we check `opcode === ATT_OP_MTU_RESP` if that's `true` we set it to 256, otherwise to 23. In the same file I can debug (on line 294 in gatt.js) that the `newMtu` variable is 50. He can log the same on his side.

The developer handling the CC2650 says he doesn't set the MTU anywhere. I'm not a C-coder, so I'm having difficulties telling if the statement is correct or not. 

Are we setting MTU to 50 somehere?

**Comment by sandeepmistry** [comment]
> Are we setting MTU to 50 somewhere?

@peturh I suspect the TI side is negotiating an MTU of 50 bytes, this might be the default in their BLE stack.

You can confirm this via ```sudo hcidump -t -x```.
