### ISSUE TITLE
How to deploy on Mac OS X without requiring XCode?

### ISSUE THREAD

**Issue by miniBloq** [sandeepmistry/noble#406]
Hi, I need to deploy an app written in Node.js as a desktop application, and it's not possible at all to make it mandatory for the end users to install the full XCode stuff on their Macs. Is it possible to deploy Node.js apps using noble without the XCode requiriment?
Thx!

**Comment by sandeepmistry** [comment]
@miniBloq what have you tried so far?

I think you can just bundle the `node_modules/noble` folder from your Mac with the rest of your app.

**Comment by miniBloq** [comment]
Hi @sandeepmistry, thanks! I just tested on a clean Mac (without XCode or any other dev stuff installed) and it just worked!

**Comment by sandeepmistry** [comment]
@miniBloq awesome!
