### ISSUE TITLE
OCF_LE_SET_EVENT_MASK is defined but not used in hci.js

### ISSUE THREAD

**Issue by bvwelch** [sandeepmistry/noble#410]
Your project is amazing! And very useful! thank you.

This is may be a small typo -- instead of using this value, the similar OCF_SET_EVENT_MASK is used, when creating LE_SET_EVENT_MASK_CMD. This is harmless, since they both have a value of 1.

**Comment by sandeepmistry** [comment]
@bvwelch thanks for pointing this out!

I've correct this in https://github.com/sandeepmistry/noble/commit/710bd8b1ba140a2a899111760bf71e5ef7291546.
