### ISSUE TITLE
Can I 'gulp' it 'browserify'?

### ISSUE THREAD

**Issue by TomasPangzi** [sandeepmistry/noble#414]
Can I 'gulp' it 'browserify'?

**Comment by monteslu** [comment]
@TomasPangzi you can browserify it.  Right now it will attempt to use websocket bindings to a local server that will proxy the noble calls from the browser to nodejs.

If you want it to use webbluetooth, you can try browserifying my fork:  https://github.com/monteslu/noble
Would love some help in testing that fork :)

**Comment by TomasPangzi** [comment]
@monteslu Thank you.

**Comment by sandeepmistry** [comment]
@monteslu thanks for helping @TomasPangzi out!
