### ISSUE TITLE
Not able to receive advertisement after receiving onces

### ISSUE THREAD

**Issue by shirish47** [sandeepmistry/noble#417]
I am trying out noble example advertisement-discovery.js on intel edison with the nrf51822 and my devices work perfectly...
but after receiving advertisment displaying it on console .. edison does not show the advertisement again.. I am putting my data in adv packet other devices(other nrf51822) show the updated adv packet.

how does noble handle this in background ?? does it store mac address and does not call respective methods after one call ?? 

I understand that silenting the device advertisement will help or else it would be to much on console to read. how should I get all advertisement? because my project is updating data and advertising it on manufacturing type.. I don't preffer connection based right now.. pls let me know.. :) thanks in advance.

**Comment by sandeepmistry** [comment]
Hi @shirish47,

Please see the read me: https://github.com/sandeepmistry/noble#start-scanning

I think you want to start scanning with duplicates: ```noble.startScanning([], true```
