### ISSUE TITLE
Address appears as "unknown" on Mac OS X 10.11

### ISSUE THREAD

**Issue by seldenr** [sandeepmistry/noble#424]
I have installed noble as instructed and have Xcode installed. When I run the enter-exit.js file from the examples, all of my addresses found are "unknown". I verified on an Ubuntu machine that they are advertising correctly, noble finds their addresses correctly.

Please let me know what log files would be helpful to post, or anything else needed to find the issue.

Thanks!

**Comment by sandeepmistry** [comment]
Hi @seldenr,

I've added a note about this to the read me in https://github.com/sandeepmistry/noble/commit/b0f5d8fdb61e550211c38e1297b7328bbed1bc14.

https://github.com/sandeepmistry/noble/blob/master/README.md#peripheral-discovered

> on OS X the address will be set to 'unknown' if the device has not been connected previously.
