### ISSUE TITLE
writeHandle withoutResponse does not work in Ubuntu

### ISSUE THREAD

**Issue by carlosamtech** [sandeepmistry/noble#433]
https://github.com/sandeepmistry/noble/blob/master/lib/websocket/bindings.js Line 292.
This 2 methods call the same action readHandle?
NobleBindings.prototype.readHandle = function(deviceUuid, handle) {
  var peripheral = this._peripherals[deviceUuid];
  this._sendCommand({
    action: 'readHandle',
    peripheralUuid: peripheral.uuid,
    handle: handle
  });
};
NobleBindings.prototype.writeHandle = function(deviceUuid, handle, data, withoutResponse) {
  var peripheral = this._peripherals[deviceUuid];
  this._sendCommand({
    action: 'readHandle',
    peripheralUuid: peripheral.uuid,
    handle: handle,
    data: data.toString('hex'),
    withoutResponse: withoutResponse
  });
};
THANKS!!!!

**Comment by sandeepmistry** [comment]
@carlosamtech please submit a pull request for this, the action should be `writeHandle` in `writeHandle`.

**Comment by carlosamtech** [comment]
THANK YOU!
