### ISSUE TITLE
var noble = require('noble'); should not immediately start listeners 

### ISSUE THREAD

**Issue by roycwc** [sandeepmistry/noble#442]
#299 

Once i call 
`var noble = require('noble');`

the script keep listening and I can't find a way to stop it except Ctrl+C.

I think there should be some start/stop listening method for us to do it manually. eg.
```
noble.startListen();
noble.stopListen();

noble.onStartListen(function(){
  // etc...
})
```

**Comment by sandeepmistry** [comment]
@roycwc this is not supported currently.

https://github.com/sandeepmistry/noble/issues/299 is already open to track this.
