### ISSUE TITLE
Noble Scan Parameters , internal - window

### ISSUE THREAD

**Issue by ozanAta** [sandeepmistry/noble#448]
Hello,
When i use noble for BLE scan, time difference between two signals can go up to  40 seconds, but when do the scanning on my mobile phone (using estimote's app) it's getting a signal every second. I tried changing interval and window parameters on `lib/hci-socket/hci.js` but i didn't worked, how can i change the scanning parameters to get 900ms of scanning time and 100ms rest time. Thank you so much for your help.

**Comment by sandeepmistry** [comment]
Hi @ozanAta,

Please see the discussion in https://github.com/sandeepmistry/noble/issues/303.
