### ISSUE TITLE
Not finding all devices

### ISSUE THREAD

**Issue by tellandev** [sandeepmistry/noble#450]
Hi

I am using Noble on a Raspberry Pi 3 and it is not managing to find my Samsung S7, a Jaguar car kit or an  iPhone 5 when doing a scan. It is however finding some of the BLE sensors I have. If I use the scan build into Jessie on the Pi it finds all the phones and the BLE devices we have. Are they getting filtered out or do I need to do a different kind of scan to find phones and car kits?

**Comment by sandeepmistry** [comment]
Hi @tellandev.

Please try: https://github.com/sandeepmistry/noble#reporting-all-hci-events

**Comment by tellandev** [comment]
Hi

Thanks for that but I think I have a different issue. If I run your enter
exit example it never picks up car kits or cell phones. Only beacons and
other BLE devices. For my use case, I just need to detect car kits and
phones but not connect to them.

Hope that makes sense

On 24 Aug 2016 01:08, "Sandeep Mistry" <notifications@github.com> wrote:
>
> Hi @tellandev.
>
> Please try:
https://github.com/sandeepmistry/noble#reporting-all-hci-events

**Comment by tellandev** [comment]
Hi

I viewed this on a phone and it did not jump to the bookmark as you intended and displayed bits fr pulse. Just viewed your link on a desktop and it looks good. I will try it in the morning.

Thanks

**Comment by tellandev** [comment]
Hi @sandeepmistry 

I have tried the reporting all hci events and I still do not get the phones or car kits near by. Any ideas?

**Comment by sandeepmistry** [comment]
@tellandev what command are you using to scan for devices outside of noble?

noble will only report BLE advertisements. If your "phones or car kits near by." are Bluetooth Classic this will not work. For iPhone you can use an app like LightBluetooth to make the phone advertise using BLE.

**Comment by tellandev** [comment]
Hi @sandeepmistry 

I think that is the problem then. The devices I need to detect are more likely Bluetooth Classic but I need to be able to detect both Bluetooth Classic and BLE devices for the project I am working on. Would it be possible for you to point me in the right direction to modify noble to work with Classic also or is that simply not possible?

**Comment by sandeepmistry** [comment]
> Would it be possible for you to point me in the right direction to modify noble to work with Classic also or is that simply not possible?

You can modify [lib/hci-socket/hci.js](https://github.com/sandeepmistry/noble/blob/master/lib/hci-socket/hci.js) to add an HCI command to start a normal scan and listen for the relevant event(s) for non-LE devices.

I'm going to close this as noble is for BLE devices only.

**Comment by tellandev** [comment]
Thanks Sandeep. I will make the changes on a local copy.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
can you tell me how to do this?

i try to locate iphones in my house with this but without luck... 

thanks

**Comment by jaewonha** [comment]
@sandeepmistry @tellandev would you share what changes did you made at the file?
