### ISSUE TITLE
Problem with getting data from blend micro (Red Bear lab)

### ISSUE THREAD

**Issue by rusyabob** [sandeepmistry/noble#451]
blend micro send message "Hello World" every second, and my raspberry pi 3 has to read this message by bluetooth. I am connecting to device, but I can't understand how to get this message. Can you help me?  I am using your code from https://github.com/sandeepmistry/noble/blob/master/test.js

**Comment by sandeepmistry** [comment]
Hi @rusyabob.

test.js is not really a useful in your scenarios. I suggest you try one of these:

 * https://www.npmjs.com/package/nrfuart
 * https://www.npmjs.com/package/node-uartble

Both build upon noble to hide the Nordic UART profile RBL is using. They will be much easier to use than noble directly.
