### ISSUE TITLE
Connection event callback

### ISSUE THREAD

**Issue by petertorelli** [sandeepmistry/noble#457]
Is there an API to register a callback that will be called on every connection event (excluding skipped ones, obviously)?

**Comment by sandeepmistry** [comment]
Hi @petertorelli,

Could you please clarify what you mean by "connection event"?

**Comment by petertorelli** [comment]
Sorry, I meant "interval" not "event". I'm referring to 7.5ms/4s connection interval. I'm experimenting with synchronizing some wakeup code on a sleepy edge node, and rather than use setInterval I thought I could hook into the hardware. Thanks!

**Comment by sandeepmistry** [comment]
@petertorelli nope there are no hooks from the adapter when the "connection interval" period happens. We could only emit an event when it changes (on first connect or re-neogiate).

**Comment by petertorelli** [comment]
Thanks for the reply.
