### ISSUE TITLE
Installing noble on windows

### ISSUE THREAD

**Issue by TorstenRobitzki** [sandeepmistry/noble#461]
Hi there,
I have problems installing noble in windows (namely windows 7, but I need to support more versions of windows). Some dependency (bluetooth-hci-socket) fails to build. Is there any easy workaround for this that can easily be applied by not so technical customers?

cheers,
Torsten

**Comment by sandeepmistry** [comment]
Closing this for now, discussion moved to https://github.com/sandeepmistry/node-bluetooth-hci-socket/issues/35#issuecomment-245872352.
