### ISSUE TITLE
Build a Browser-Based Locally-Hosted GUI on Raspberry Pi 3 to control an Arduino-based Bot

### ISSUE THREAD

**Issue by jasonc1025** [sandeepmistry/noble#462]
Thanks @sandeepmistry to your professional attention to Issue #440.  

My next question is more of seeking your programming counsel.  Please advise if there's a better place to post such a non-bug-related question.  

I appreciate the excellent example from which to learn from: 'Node-Rolling-Spider' & 'Keypress' from your book, 'Make: Bluetooth' in Chapter 10's Drones.

How hard would it be to replace the 'Keypress' approach with instead a Web-based Remote-Control GUI with Touch-Buttons (vs. using the 'Keypress' module).  Essentially, I'm attaching a 3.5in Touchscreen to a RaspberryPi3 (Jessie Debian) to function as a remote-controller (the central device, much like a smart-phone with a GUI controller app).  On the receiving end (the peripheral device) is a Arduino-based bot using a Bluefruit nRF8001.

Technically, I'm seeking to provide a Browser-based GUI that is Locally-Hosted on the RaspberryPi for the following Noble instructions:

` function botForward( peripheral, characteristic ){ characteristic.write(new Buffer([0x77]), false,function(error) {}); }`
  
`function botBackward( peripheral, characteristic ){ characteristic.write(new Buffer([0x73]), false, function(error) {}); }`

`function botLeft( peripheral, characteristic ){ characteristic.write(new Buffer([0x61]), false, function(error) {}); }`

`function botRight( peripheral ,characteristic ){ characteristic.write(new Buffer([0x64]), false, function(error) {}); }`

Because I am a newbie web developer (more used to Python/C++), I naively thought I could just place the above Noble-based code within an index.html's:

`<script type="text/javascript" charset="utf-8"> & </script>`

I've been playing with stacks such as the popular Meteor down to the simple yet cool Flask, yet with various degrees of failure - ranging from 'unresolved modules' to 'no web response'.  Hopefully someone could point me to some related, helpful examples.  

As a personal background, my colleagues and I are developing a D.I.Y. Arduino-based Educational Robotics Kit for kids of all ages  : ).  Feel free to check out: www.EandE.world.

Thanks in advance... :) Jason

**Comment by jacobrosenthal** [comment]
Sandeep built the [websocket bindings](https://github.com/sandeepmistry/noble/blob/master/lib/websocket/bindings.js)  purpose. At a very high level, you open up a websocket for the front end to talk to by running `node ws-slave.js` then when you browserfy/webpack noble it should automatically package the websocket bindings and connect to your running script. Give it a try.

**Comment by jasonc1025** [comment]
Thanks @jacobrosenthal for the helpful tip.  I'll look into it.  : )
