### ISSUE TITLE
No devices discovered on macOS Sierra

### ISSUE THREAD

**Issue by BlackWolf** [sandeepmistry/noble#463]
I was stupid enough to update to the GM of Sierra and of course it broke noble. I can advertise with bleno, but when scanning for devices with noble the 'discover' event is never fired. Here is the debug output:

```
  noble addressChange a8:66:7f:3b:17:ab +0ms
  yosemite-bindings sendCBMsg: 1, {
  "kCBMsgArgName": "node-1473892881102",
  "kCBMsgArgOptions": {
    "kCBInitOptionShowPowerAlert": 0
  },
  "kCBMsgArgType": 0
} +6ms
  yosemite-bindings xpcEvent: {
  "kCBMsgId": 6,
  "kCBMsgArgs": {
    "kCBMsgArgState": 5
  }
} +5ms
  yosemite-bindings state change poweredOn +1ms
  noble stateChange poweredOn +0ms
poweredOn
  yosemite-bindings sendCBMsg: 29, {
  "kCBMsgArgOptions": {
    "kCBScanOptionAllowDuplicates": 1
  },
  "kCBMsgArgUUIDs": []
} +6ms
  noble scanStart +0ms

```

This is all I get, there is no further output. I don't know much about the inner workings of noble, but it seems that not further xpc event is triggered at all. Any ideas on this?

**Comment by BlackWolf** [comment]
Update: Turns out this was not a noble issue, but a corruption of BT after the update. For everyone experiencing this, deleting the following plists and restarting `blued` helped for me:

/Library/Preferences/com.apple.Bluetooth.plist
~/Library/Preferences/com.apple.BluetoothFileExchange.plist
/var/root/Library/Preferences/blued.plist

**Comment by sandeepmistry** [comment]
Hi @BlackWolf,

Thanks for pioneering noble on macOS Sierra!

It's good to know that the XPC id's have not changed. We're looking to move the using [node-core-bluetooth](https://github.com/sandeepmistry/node-core-bluetooth) on Mac instead of the XPC connection (which was reversed engineered, using swizzling).

You can help try it out by trying out the core-bluetooth branch: https://github.com/sandeepmistry/noble/tree/core-bluetooth

**Comment by BlackWolf** [comment]
Thanks, I will try that branch and let you know what happens on Sierra :D Can confirm that the main noble branch is Sierra compatible, though, have been running it successfully for the last couple of days.

**Comment by farfromrefug** [comment]
@sandeepmistry what's the status on this? I am facing the sierra issue

**Comment by sandeepmistry** [comment]
@farfromrefug no issues for me, I updated to Sierra last week.

**Comment by farfromrefug** [comment]
It might be the same issue as @BlackWolf  after an update. I was asking about the core-bluetooth branch. Are you maintaining it?

**Comment by BlackWolf** [comment]
@farfromrefug  Just to clarify, my issues were not related to noble at all, but purely OS X issues. I posted the steps that resolved them for me in my above post. Did you try them?

**Comment by sandeepmistry** [comment]
@farfromrefug 

> I was asking about the core-bluetooth branch. Are you maintaining it?

@jacobrosenthal and I plan to eventually merge the branch into master. If you have time to try it out and provide feedback that would be appreciated.

**Comment by akalirong** [comment]
@BlackWolf you just saved my day. Thank you so much!
