### ISSUE TITLE
Receive UUID and peripheral ID in callbacks

### ISSUE THREAD

**Issue by TheCbac** [sandeepmistry/noble#470]
Hi,

When reading a characteristic (and receiving notifications) from a peripheral, I'm surprised that read callback does not get the peripheral ID and the characteristic UUID passed in as parameters. I have multiple BLE peripherals connected simultaneously and need to know which device generated the callback. I.e. I'm looking for:

`characteristic.read([callback(error, data, peripheralId, uuid)]);`

I have a local one line hack for this in characteristic.js: 

```
Characteristic.prototype.read = function(callback) {
  if (callback) {
    this.once('read', function(data) {
      // callback(null, data);
      callback(null, data, this._peripheralId, this.uuid);
    });
  }

  this._noble.read(
    this._peripheralId,
    this._serviceUuid,
    this.uuid
  );
};
```

Is there a reason that all of the callbacks don't pass the device and characteristic that generated them? I'm I missing something? 

Thanks for this great package!
Craig

**Comment by sandeepmistry** [comment]
Hi @TheCbac,

Thanks for the feedback!

I don't think the extra args are needed. For more, complex cases I would suggest you use [noble-device](https://github.com/sandeepmistry/noble-device) to create wrapper objects for peripherals and services.

Alternatively you can use bind:

```javascript
characteristic.read(function(peripherald, characteristicUuid, error, data) {
  // ...
}.bind(this, peripheral.id, characteristic.uuid));
```
