### ISSUE TITLE
No compatible USB Bluetooth 4.0 device found on supported device (BCM20702A0 Bluetooth 4.0)

### ISSUE THREAD

**Issue by WslF** [sandeepmistry/noble#472]
Hi!

I'm trying to use noble, but I couldn't run any example(

I'm running windows 10 (build 1607) on Lenovo Y50-70 touch. My bluetooth is BCM20702A0 Bluetooth 4.0.

I follows to the video https://www.youtube.com/watch?v=mL9B8wuEdms step by step but I fails on running any example. 

```
throw new Error('No compatible USB Bluetooth 4.0 device found!');
    ^

Error: No compatible USB Bluetooth 4.0 device found!
    at BluetoothHciSocket.bindUser (D:\Programming\nodejs\node_modules\noble\node_modules\bluetooth-hci-socket\lib\usb.js:70:11)
    at BluetoothHciSocket.bindRaw (D:\Programming\nodejs\node_modules\noble\node_modules\bluetooth-hci-socket\lib\usb.js:28:8)
    at Hci.init (D:\Programming\nodejs\node_modules\noble\lib\hci-socket\hci.js:99:35)
    at NobleBindings.init (D:\Programming\nodejs\node_modules\noble\lib\hci-socket\bindings.js:83:13)
    at new Noble (D:\Programming\nodejs\node_modules\noble\lib\noble.js:50:18)
    at Object.<anonymous> (D:\Programming\nodejs\node_modules\noble\index.js:4:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

Thanks in advance.

**Comment by sandeepmistry** [comment]
Do you have the USB id's of your adapter?

If it's not in the list here: https://github.com/sandeepmistry/node-bluetooth-hci-socket#compatible-bluetooth-40-usb-adapters

You'll need to change this line to add them: https://github.com/sandeepmistry/node-bluetooth-hci-socket/blob/master/lib/usb.js#L66

Please submit a pull request with your changes if this makes things work.

**Comment by sandeepmistry** [comment]
Closed via https://github.com/sandeepmistry/node-bluetooth-hci-socket/pull/40.

**Comment by Joel0906** [comment]
Hi Sandeep/Don,

@sandeepmistry , @don 
I am using TI sensor tag CC2541 IOT hardware. I followed the youtube video "https://www.youtube.com/watch?v=mL9B8wuEdms&feature=youtu.be&t=1m46s" 

and I am getting error
throw new Error('No compatible USB Bluetooth 4.0 device found!');
    ^

Error: No compatible USB Bluetooth 4.0 device found! 

Can you please help me why the hardware Bluetooth is not getting detected . I am not sure how to know the VID and PID of my hardware as well.
IT will be a great help thanks.

 Regards,
Prince Joel

**Comment by thefakhreddin** [comment]
Hi. @sandeepmistry 
I'm using my laptop Bluetooth and I'm having a similar problem that @WslF has.
I'm using node-web-bluetooth package.

**Comment by julienrobert** [comment]
Getting the same error with Asus BT-400.
I added that id in usb.js:66 || usb.findByIds(0x0489, 0xe07a and still getting the same error.
in Windows 10 driver details :
description:BCM20702A0
path: USB\VID_0B05&PID_17CB\5CF370965774
Installed driver WinUSB 6.1.7600

using node 8.13.0
Trying to load node-red-physical-web into node-red when I get this error and node-red stops.

**Comment by michalneufeld** [comment]
hello I get the same error.
My BLE module is 
![BLE](https://user-images.githubusercontent.com/66091194/83190896-75cd1500-a133-11ea-8d23-2351a029fbba.PNG)
Software zadig says it vid: 0x8087, pid: 0x0025

Is there a chance you can add support for it?
Or somehow I can configure it?

**Comment by butkovskiim** [comment]
Hello! Same error. Can you add this device to list?
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_13D3&PID_3362&REV_0001
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_E0&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 6.1.7600.16385
libwdi:debug [wdi_create_list] WinUSB USB device (8): USB\VID_13D3&PID_3362\ALASKA_DAY_2006
libwdi:debug [wdi_create_list] Device description: 'Bluetooth USB Host Controller'

**Comment by ChristianEder** [comment]
I am getting the same error ("No compatible USB Bluetooth 4.0 device found!") although I have a Bluetooth adapter listed in the supported devices here (see screenshot below): https://github.com/noble/node-bluetooth-hci-socket#compatible-bluetooth-40-usb-adapters

I am using https://www.npmjs.com/package/node-ruuvitag/v/4.6.1, which in turn uses noble

![image](https://user-images.githubusercontent.com/5071660/202125037-3102b363-74df-4c26-ab97-df038ec78113.png)
