### ISSUE TITLE
read characteristic doesn't show proper string even after .toString('utf8')

### ISSUE THREAD

**Issue by pangrr** [sandeepmistry/noble#482]
characteristic.read((error, data) => {
console.log(data.toString('utf8'));
});

prints unrecognizable characters.

**Comment by sandeepmistry** [comment]
@pangrr your issue report is very vague please provide more details, are you sure the buffer contains the data you expect it to?

Please provide more details on what the data buffer contains (hex values) and what you expect it to.

Please note the data is a [Node.js buffer](https://nodejs.org/dist/latest-v4.x/docs/api/buffer.html).

**Comment by pangrr** [comment]
toJASON() works. toString() doesn't.

**Comment by sandeepmistry** [comment]
Hi @pangrr,

Please see my previous comment. It is pretty much impossible to help you out unless you provide more details, including the ones that I have previously requested.

I'm going to close this for now, please re-open with the requested information.
