### ISSUE TITLE
Write > 60 bytes to characteristic

### ISSUE THREAD

**Issue by estutzenberger** [sandeepmistry/noble#484]
Hi sandeep,

I'm using OS X El Capitan.  I have installed the latest version of noble.  My Bluetooth device is performing an MTU Exchange request with OS X and ends up with an MTU of 104.

However, when I try to write more than 60 bytes to a characteristic (that has a max length of 104), I never see the data on the device side.  It seems like OS X is never sending the data and I'm wondering if this has anything to do with the XPC called to blued in noble.

Any help or insight would be appreciated.  If this is currently a limitation of noble, then that is also fine.

Thanks,

Eric

**Comment by sandeepmistry** [comment]
@estutzenberger please share a minimal code example to reproduce the issue and debug logs (`DEBUG=* node <file>.js`).

Also, have you tried to do a similar thing from a native CoreBluetooth app like LightBlue on OS X?

**Comment by estutzenberger** [comment]
So, this turned out to be bad migration documentation by our Bluetooth stack vendor.  While they covered information on how to increase the MTU size, they failed to disclose the BLE event buffer size was not automatically updated.  Thus, the BLE event buffer on the device side was too small and caused a reset on > 62 byte writes.
