### ISSUE TITLE
Set Noble scan speed

### ISSUE THREAD

**Issue by davidmessem** [sandeepmistry/noble#491]
Please tag this as an enhancement request

Please can a feature be added to change the interval that Noble scans for peripherals at?
For example, I want Noble to only scan for peripherals every 1 second

**Comment by sandeepmistry** [comment]
Hi @davidmessem,

This is a duplicate request of https://github.com/sandeepmistry/noble/issues/298 - so I will close as a duplicate.

Please note, this feature would be possible on Linux, however it is not possible on OS X because CoreBluetooth does not provide this feature.
