### ISSUE TITLE
Bluetooth 4.0 (non-BLE)

### ISSUE THREAD

**Issue by denkomanceski** [sandeepmistry/noble#501]
Is it possible to use this as a "server", where my phone will connect and pair, and than send data like JSON objects etc? The phone can use cordova plugin, or nativescript native APIs.. If its not, do you guys know any module that can help me build normal non-BLE bluetooth server/client?

**Comment by gfwilliams** [comment]
I think you're after `bleno`. That allows device to act like a peripheral, so it can be connected to.

**Comment by denkomanceski** [comment]
@gfwilliams Isnt bleno for BLE only ? I need module for the normal high bandwidth bluetooth 4.0

**Comment by gfwilliams** [comment]
Yes, it is. I missed that bit.

**Comment by sandeepmistry** [comment]
@denkomanceski I'm not aware of any non-BLE libraries.
