### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by radpet** [sandeepmistry/noble#511]
Hello, 

I have trouble finding Samsung galaxy S3 Neo device using noble. My bluetooth dongle is 4.0 and the device I am looking for is also BLE. I am using Linux and I can find the device with the hcitool scan command, I have written a python script too using pybluez and it found the devices as well. Any ideas why noble can't find anything?

**Comment by sandeepmistry** [comment]
@radpet please share an HCI dump capture: `sudo hcidump -t -x`.

>  I am using Linux and I can find the device with the hcitool scan command

What's the exact command you are using? `hcitoool lescan` is for BLE devices, this module only supports BLE devices, not classic devices.

**Comment by radpet** [comment]
`sudo hcidump -t -x.` gives:
```
HCI sniffer - Bluetooth packet analyzer ver 5.37
device: hci0 snap_len: 1500 filter: 0xffffffffffffffff
```

I use `hcitool scan to find it`, `hcitool lescan does not find anything`, strange I, maybe the bluetooth inside the S3 Neo is not really ble just support pairing with ble devices. Thanks

**Comment by sandeepmistry** [comment]
@radpet ok, definitely a Bluetooth Classic device then.

You need to run an app like nRF Master Control panel to put the device into BLE peripheral mode for it to work with noble. Not sure if this will be supported by your device/Android version.
