### ISSUE TITLE
discoverSomeServicesAndCharacteristics order

### ISSUE THREAD

**Issue by llemtt** [sandeepmistry/noble#515]
I'm trying to use discoverSomeServicesAndCharacteristics but I can't understand in which order characteristics are returned...

Any suggestion on how to find and use just few characteristics?

Thanks

**Comment by sandeepmistry** [comment]
@llemtt 

> I'm trying to use discoverSomeServicesAndCharacteristics but I can't understand in which order characteristics are returned...

The order should match the order the peripheral has them set to.
