### ISSUE TITLE
Bug: Calling connect on powered down peripheral causes noble to hang

### ISSUE THREAD

**Issue by aj-ptw** [sandeepmistry/noble#522]
Steps to reproduce:
* Power up device
* Scan for a peripheral with noble
* Find the `peripheral` you want, save to var.
* Stop scanning
* Power down device
* Call `connect` in noble with `peripheral`

Noble hangs forever :(

**Comment by sandeepmistry** [comment]
@aj-ptw are you using noble on Linux or Mac?

**Comment by mattgol** [comment]
I noticed the same behavior (on Linux). I'm not sure if this qualifies as a bug though: The BT dongle keeps trying to connect until a cancel is sent. (Mine blinks furiously during connection so I can easily distinguish from normal operation.) After powering up the device everything turns back to normal. I solved this problem by adding a timeout to my connection attempt. However, for canceling on Linux the patch described in [#229](https://github.com/sandeepmistry/noble/issues/229) is necessary. On Macs simply a call to disconnect is sufficient.

**Comment by sandeepmistry** [comment]
Closing this issue due to lack of feedback on the original topic.

**Comment by benjaminhon** [comment]
I also have this issue, calling connect when the peripheral is in another state other than 'disconnected' causes noble to hang or go into an unrecoverable state

**Comment by Jaftem** [comment]
Happens to me as well. I believe this is because of the connection queue. Connection attempts after the hanging connection attempt are never actually attempted.
