### ISSUE TITLE
System Stalls After X amount of time 

### ISSUE THREAD

**Issue by freebeans** [sandeepmistry/noble#525]
I have the same problem discussed in #314.
I'm scanning beacons for long periods of time and publishing their UUIDs via mqtt. After some time my application stops discovering them with no apparent error. I'm using RPi 3 and bluez 5.23-2+rpi2.

When I restart my application, it works fine again.

**Comment by sandeepmistry** [comment]
@freebeans please provide and HCI dump capture: `sudo hcidump -t -x`

**Comment by sandeepmistry** [comment]
Closing for now due to lack of activity.
