### ISSUE TITLE
StartScanning returns error value of true

### ISSUE THREAD

**Issue by mbifulco** [sandeepmistry/noble#537]
@sandeepmistry - is there a better way to tell what's going on when I get errors from `startScanning`?

I need to continually check for BLE devices with my app, so I run the following:

```javascript
noble.on('scanStop', function(state){
    log.debug("Detected bluetooth scan stop - scanning again")
    noble.startScanning(Constants.SERVICE_UUIDS, false, (err) => {
        if (err) {
            log.error("startScanning error [2]: " + err);
        }
    });
});
```

Fairly regularly, this code returns an error, meaning I see
> startScanning error [2]: true

In my console at runtime.  I'd love to know what's going wrong, so I can work around it.

**Comment by sandeepmistry** [comment]
This should be fixed by https://github.com/sandeepmistry/noble/pull/530 which @MarSoft submitted.

Could you please try again with the master version of noble and let us know?

**Comment by mbifulco** [comment]
@sandeepmistry @MarSoft just like that, no more errors! Will this make its way into a release soon?

**Comment by mbifulco** [comment]
ping @sandeepmistry - any idea when you'll push a release?

**Comment by sandeepmistry** [comment]
@mbifulco v1.8.0 was just published to npm.
