### ISSUE TITLE
Connect to previously discovered device

### ISSUE THREAD

**Issue by mattotodd** [sandeepmistry/noble#539]
The Pizza example says that peripherals [can also be constructed if the uuid is already known](https://github.com/sandeepmistry/noble/blob/master/examples/pizza/central.js#L42)

Do you have an example of this?

The only way I saw was to call `noble.onDiscover` with saved values from `preripheral.toString()` to let noble know about the peripheral. Trying to connect to the peripheral after that just hangs in a `connecting` state.

Normal discovery works fine and I can connect to the peripheral

**Comment by mbifulco** [comment]
@mattotodd - in my project, I'm calling 
`peripheral.once('connect')` within `noble.on('discover')` connect to peripherals each time they reconnect after being initially discovered.

I call `peripheral.connect();` at the very end of my `noble.on('discover')` callback to trigger a connection when the device returns into range.  Roughly, in pseudocode, it looks like this:


```
noble.onDiscover( (peripheral) => {
    peripheral.once('connect', () =>{
       do whatever you need with this peripheral when it is connected
    });

   peripheral.connect(); // trigger the connection to this peripheral
});
```

**Comment by sandeepmistry** [comment]
@mattotodd that comment is inaccurate, I've removed it in https://github.com/sandeepmistry/noble/commit/b03e852ea7a2ae65386579a38e821a302e32292a.
