### ISSUE TITLE
Error: Could not start scanning, state is unknown (not poweredOn)

### ISSUE THREAD

**Issue by YYogi** [sandeepmistry/noble#544]
Hi Sandeep,
I am trying to scan for BLE devices but i keep getting this error

Error: Could not start scanning, state is unknown (not poweredOn)

This is the code I am using:
var noble= require('noble');

noble.on('stateChange', function(state) {
  if (state === 'poweredOn') {
    noble.startScanning();
  } else {
    noble.stopScanning();
  }
});

noble.startScanning();

noble.on('discover',function(peripheral){

  var macAddress = peripheral.uuid;
  var rss = peripheral.rssi;
  var localName = advertisement.localName;
  console.log('found device: ', macAdress,' ',localName,' ', rss);
});

And this my Bluetooth version:
sudo hciconfig hci0 version
hci0:   Type: BR/EDR  Bus: UART
        BD Address: B8:27:EB:E7:E7:BA  ACL MTU: 1021:8  SCO MTU: 64:1
        HCI Version: 4.1 (0x7)  Revision: 0xb6
        LMP Version: 4.1 (0x7)  Subversion: 0x2209
        Manufacturer: Broadcom Corporation (15)

**Comment by sandeepmistry** [comment]
@YYogi please see the note section here: https://github.com/sandeepmistry/noble#start-scanning
