### ISSUE TITLE
Lookup of undiscoverable device

### ISSUE THREAD

**Issue by jdrucey** [sandeepmistry/noble#547]
Is it possible to perform a lookup of a given address in Noble?

Much like PyBluez does for Python:
`bluetooth.lookup_name('CC:20:E8:8F:3A:1D', timeout=5)`

This can find the device even if it is undiscoverable, unlike a typical inquiry scan would.

Apologies if this is redundant or in the wrong place!

**Comment by sandeepmistry** [comment]
@jdrucey 

> Is it possible to perform a lookup of a given address in Noble?

No, this is not supported in noble - scanning is required before connecting.

Please nope inquiry scan is for Bluetooth Classic, and not for BLE only devices which this library targets.
