### ISSUE TITLE
Not scanning with windows internal bluetooth

### ISSUE THREAD

**Issue by dharmeshpurohit** [sandeepmistry/noble#548]
Hi 

I tried with Bluetooth USB Dongle and installed USB Driver Zodig and everything is working fine. 

But my requirement is I want to run bluetooth scanner on my Windows 10 Table on internal bluetooth.

Is there way I can make noble work for my requirement? Or any other package I should be using?

I did looked at WinBLE but it requires pairing which is not making sense to me. 

Dharmesh

**Comment by sandeepmistry** [comment]
If you internal Bluetooth adapter is USB based, yes.
