### ISSUE TITLE
Can this support Bluetooth 4.2 version?

### ISSUE THREAD

**Issue by gyloh9210** [sandeepmistry/noble#549]
Hi there, I was wondering can noble support up to bluetooth 4.2 version? I am using my internal built-in bluetooth inside my laptop but I could not get it working. It is keeping loading and no responding at all when I run node index.js or node test.js. Please help.

**Comment by sandeepmistry** [comment]
@gyloh9210 should be fine, I would suggest trying the advertisement discovery example in the examples folder.

**Comment by gyloh9210** [comment]
However, what i got is no response at all. Any clue?

**Comment by sandeepmistry** [comment]
Are you using mac or linux?

**Comment by gyloh9210** [comment]
Windows 10

**Comment by sandeepmistry** [comment]
Please provide debug logs:

```
setenv DEBUG=*
node examples/advertisement-discovery.js
```

**Comment by gyloh9210** [comment]
Hey somehow its working while running advertisement discovery script. Thank for your reply!!
