### ISSUE TITLE
Unexpected results in 1.8.0 

### ISSUE THREAD

**Issue by aj-ptw** [sandeepmistry/noble#554]
Upgrading code from `v0.1.7` to `v0.1.8` results in no received, possibly no data sent, need more tests but developing over https://github.com/OpenBCI/OpenBCI_NodeJS_Ganglion/pull/24 in the Ganglion library.

**Comment by sandeepmistry** [comment]
Hey @aj-ptw,

Unfortunately this issue report is very vague and not helpful to the noble community at this time.

I'm going to close it for now, until you can provide more details to help us track down the issue. Things that would help include a minimal sample noble app that can used to demonstrate the issue with v1.8.0 of noble but shows that v1.7.x was working. Thanks.
