### ISSUE TITLE
Incomplete typings

### ISSUE THREAD

**Issue by ZLima12** [sandeepmistry/noble#555]
I am using TypeScript, and after installing @types/noble, it doesn't seem like the typings include some properties. The one that made me notice it is `Noble.state`, but I'm not sure if there are any others missing.

**Comment by sandeepmistry** [comment]
Hey @ZLima12,

There are no official typings for noble, I think you're referring to the ones hosted here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/noble

I suggest you open a issue or PR there to address this. Thanks.
