### ISSUE TITLE
Start scanning on multiple HCI-devices not possible

### ISSUE THREAD

**Issue by TommaHawk** [sandeepmistry/noble#578]
I want to create an application, which scans for devices on multiple HCI-devices ( up to 3 dongles) 
that's why I tried to set NOBLE_HCI_DEVICE_ID and create new Noble Objects (from noble/lib/noble.js) but the second noble do not start.

might be cause the binding is always the same object (module.exports = new NobleBindings(); in hci-socket/bindings.js)

so it would be nice to have the feature to scan on multiple bluetooth dongles

here is some example code

```
import Noble from 'noble/lib/noble';
import bindings from 'noble/lib/resolve-bindings';

var initNoble = function (noble) {
  noble.on('stateChange', function (state) {
    if (state === 'poweredOn') {
      noble.startScanning();
    } else {
      console.log('noble powered OFF');
    }
  });
}
let scan = function(hciId){
  process.env.NOBLE_HCI_DEVICE_ID = '' + hciId;
  let noble = new Noble(bindings());
  initNoble(noble);
}

scan(0);
scan(1);
scan(2);

```

**Comment by sandeepmistry** [comment]
The main goal of this project is a uniform API for all supported platforms (macOS, Linux, Windows, web bluetooth etc).

Feel free to fork and mod the source to get what you want working :)
