### ISSUE TITLE
Is there noble npm package for anuglar2 implementation?

### ISSUE THREAD

**Issue by narada85** [sandeepmistry/noble#579]
I'm trying to integrate noble with angular2 app. but still couldn't bind events.

**Comment by jacobrosenthal** [comment]
Theres webbluetooth now, mostly just supported by chrome, and there is a binding from @monteslu that maps that api to the noble api
https://github.com/sandeepmistry/noble/tree/master/lib/webbluetooth
He has a demo running https://noble.surge.sh/

Thats normally packaged for the front end via Webpack or browserify, but I have no idea for angular.

Or you can use the websocket binding people have used on say raspberry pis most commonly to send the bluetooth apis to a separately running node script
https://github.com/sandeepmistry/noble/tree/master/lib/websocket

**Comment by narada85** [comment]
@jacobrosenthal, thanks for the reply!
