### ISSUE TITLE
Linux install calls for blues-utils which doesn't exist for Raspbian

### ISSUE THREAD

**Issue by stasiana** [sandeepmistry/noble#592]
The documentation claims that noble works for Raspberry Pi and the [wiki](https://github.com/sandeepmistry/noble/wiki/Getting-started) says to install dependencies as follows:

> `sudo apt-get install bluetooth bluez-utils libbluetooth-dev
`

But `bluez-utils` doesn't exist for Raspbian. What should be the list of dependencies to get noble installed properly on Raspbian for Raspberry Pi?

**Comment by sandeepmistry** [comment]
The wiki is out of sync with the read me: https://github.com/sandeepmistry/noble#ubuntudebianraspbian

I've updated it with: `sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev`

@stasiana thanks for bringing this up.
