### ISSUE TITLE
Not scanning without parallel hcitool lescan command

### ISSUE THREAD

**Issue by Cosmopal** [sandeepmistry/noble#594]
I have used the following script:

```
var noble = require('noble');
console.log('started');	

noble.state="poweredOn";

noble.startScanning([], true);

noble.on('discover', function(peripheral) { 

  var macAddress = peripheral.uuid;
  var rss = peripheral.rssi;
  var mandata = peripheral.serviceData;
  var connecteble = peripheral.connectable;
  console.log("Hello World!");
  console.log('found device: ', macAddress, ' ', rss,' ', tx,' ',mandata,' ',connecteble);
  }
});

```
The problem is that the function does not start scanning the ble beacons until I enter `sudo hcitool lescan` in a parallel terminal

**Comment by Cosmopal** [comment]
I tried writing a bash script, launching the script first and then doing hcitool lescan, but then it got me only one beacon.

**Comment by sandeepmistry** [comment]
I've corrected this in https://github.com/sandeepmistry/noble/commit/7e96ad519ccc146d394c833d2eb7d3dd012c0405. Please try with `npm install sandeepmistry/noble` and report your feedback.
