### ISSUE TITLE
does noble can run as an peripheral and central?

### ISSUE THREAD

**Issue by DanielTimLee** [sandeepmistry/noble#595]
In BLE 4.x, GAP Profile has some profiles, mostly the one who really provides data (Peripheral), and the other one who collects data (Central).

Peripheral Advertises itself, and wait for Central's connection request.

I think `noble` just have only Central role. I can't find` noble` doc that says it advertises itself to other Central Devices.

Am I right?... (I'm not sure about this).. **Does `Noble` has Advertising function? (advertise itself device)**
If there are no Peripheral role (such as Advertising itself) in `noble` , then will does Peripheral role is it planned to be developed?

**Comment by jacobrosenthal** [comment]
I believe you're looking for [bleno](https://github.com/sandeepmistry/bleno)
