### ISSUE TITLE
Having issue discovering characteristics after manually disconnecting.

### ISSUE THREAD

**Issue by renay007** [sandeepmistry/noble#605]
After manually disconnecting using React Native, characteristics are showing as null once the services are discovered.

I'm referencing it to #520. I'm thinking it is the same issue. Any help would be greatly appreciated.

`    _onDiscover(peripheral) {
      noble.stopScanning();
      var peripheralIsConnected = function () {
        noble.stopScanning();                                                                                                                                                     
      }                 
      var peripheralIsDisconnected = function () {
		console.log('user disconnected');
      }                 
      peripheral.once('disconnect', peripheralIsDisconnected);
      if (peripheral.advertisement.localName == BLE_localName) {
        peripheral.connect(function(err) {
          console.log('successful connection');
          peripheral.discoverServices(null, function(err, services) {
            if (err) {  
              console.log('error retrieving services');
              console.log(err);
            }           
            console.log('services discovered');
            console.log(services);
            services.forEach(function(service) {
              console.log('about services');
              console.log(service);
              service.discoverCharacteristics(null, function(err, characteristics) {
                  if (err) {
                    console.log('error retrieving characteristics');
                    console.log(err);
                  }     
                  console.log('characteristics discovered');
                  console.log(characteristics);
                        
                characteristics.forEach(function(characteristic) {
                  switch (characteristic.uuid) {
                    case isOnCharacteristicUuid:
                        isOnCharacteristic = characteristic;
                        break;
                    case isRunningCharacteristicUuid:
                        isRunningCharacteristic = characteristic;
                        break;
					default:
						break;
                  }    
                })
                  if (true) {
                    console.log('subscribing');
                    isOnCharacteristic.once('read', function(data, isNotification) {
                        console.log('isOnCharacteristic data');
                        console.log(data);
                    });
                    isOnCharacteristic.subscribe(function(err) {
                      if (err) {
                        console.log('isOnCharacteristic: subscribe error : '+ err);
                      } else {
                        console.log('isOnCharacteristic: subscribe success');
                      }
                    });
                  } else {
                    console.log('missing characteristics'); 
                  }
             
              })
            })
          })                                                                                                                                                                      
        })   
        peripheral.once('connect', peripheralIsConnected);
      }`

**Comment by sandeepmistry** [comment]
Hey @renay007,

This library doesn't support React Native, maybe you mean't to open an issue here instead? https://github.com/jacobrosenthal/react-native-ble/issues
