### ISSUE TITLE
when advertisement data become null, it cache last one

### ISSUE THREAD

**Issue by javaxiu** [sandeepmistry/noble#609]
my ble device broadcast data in advertisement data area, and it changes times to times,
in this case:

a few seconds ago, adv data got a buffer like 
`peripheral.advertisement.manufacturerData: 0101000f000700000007000300f200c901b50ede`

and now adv data, some how ,is null from device, but i still got
`peripheral.advertisement.manufacturerData: 0101000f000700000007000300f200c901b50ede`

i believe this issue came from javascript Object reference, `peripheral.advertisement` is the same one Object and when advdata is null we should execute `'delete peripheral.advertisement.manufacturerData'` to avoid this issue

i guess it is in `../build/Release/binding.node` file?

**Comment by sandeepmistry** [comment]
@javaxiu this is the expected behaviour from noble, it stores the old data and "or's" in the new: https://github.com/sandeepmistry/noble/blob/master/lib/hci-socket/gap.js#L98-L238

If you have a proposal to change this, please open a pull request.
