### ISSUE TITLE
Make use of Noble 

### ISSUE THREAD

**Issue by fafa92** [sandeepmistry/noble#616]
Hi, I'm kind of new to this library, so basically, I want to make use of it and I ran some examples of it, like  advertisment-discovery.js and enter-exit.js, but I want to scan for possible BLE devices that are close to me with noble.startScanning(); which can give me back UUID and minor and major which I want to use, So anyone can help me about how can I start to use it? and does this library support Eddystone packets as well? or should I use another one like "node-eddystone-beacon-scanner"? I'll be happy to hear from those who have experience.

**Comment by jacobrosenthal** [comment]
You could write that from scratch, but this library is used by other libraries that have already done that. 
https://github.com/sandeepmistry/node-bleacon
https://github.com/sandeepmistry/node-eddystone-beacon-scanner
