### ISSUE TITLE
Unreliable signal detection?

### ISSUE THREAD

**Issue by kaYcee** [sandeepmistry/noble#628]
Great package! One thing I noticed though is that with a beacon that send at a constant rate (e.g. 500ms), the noble scanner starts working correctly, but after short time it "swallows" some signals only to push them out in a row a couple of seconds later, sometimes the delay is a couple of seconds. Usually that's not a big deal but I am trying to get a realtime detector running and it currently triggers a lot of false alarms over a day. I am using the latest version on RPi3. Thanks!

Forgot to mention that in order to rule out problems with the beacon I tried also with python PyBluez package which does not show this kind of behaviour.

**Comment by sandeepmistry** [comment]
@kaYcee maybe you could share your code and an HCI dump capture (`sudo hcidump -t -x`) along with the debug output.

**Comment by cruepprich** [comment]
kaYcee, 
I'm trying to get noble running on my Pi3, but get all kinds of errors. Which OS are you running? Did you have to do anything special to get noble going?

Thanks!

**Comment by bastianleirpo** [comment]
We are having the same issue here. Any solutions so far? 
It might be the same problem than reported #596
We are using: Raspberrry Pi 3 b, internal Bluetooth sensor, noble 1.8.1, up-to-date raspberian via noobs, Estimote beacons

**Comment by sandeepmistry** [comment]
@bastianleirpo please provide info requested in https://github.com/sandeepmistry/noble/issues/628#issuecomment-309278901 then we can re-open this.

I'm closing it due to lack of activity for now.
