### ISSUE TITLE
Unable to install noble on Win7 [SOLVED]

### ISSUE THREAD

**Issue by Xan-Kun** [sandeepmistry/noble#629]
Hello!
I am running Win7/x64 and initially had the error seen at the end.
I figured out that the problem (as usual) was my, well, "unthoughtfullness" and just to round things up, I wanted to summarize how it definitely works:

install **.NET 4.5.1** (I used the redist version _NDP451-KB2858728-x86-x64-AllOS-ENU_)
install **python-2.7.13.msi**
install **node-v6.10.3-x64.msi**
install **WinUSB** driver with zadig
run `npm install --global --production windows-build-tools`
run `npm install`

try examples
`node examples\advertisement-discovery.js`
`node examples\peripheral-explorer.js abcdef123456` (where abcdef123456 is your device id)

I ran all npm and following commands in an elevated node-console (`cmd.exe /k "C:\Program Files\nodejs\nodevars.bat"`).
The working directory was always the `noble-master` folder.

Note, that I did not have to install node-gyp, as the version that comes with node seems to work fine for now.
There was also no need to set the msvs version (e.g.: `set GYP_MSVS_VERSION=2015`, `npm config set msvs_version 2015 --global` or whichever version).
It worked straightaway and I succesfully got the advertisement info and the services and characteristics from the device in question.

Without .NET installed, I got the following error message:

```
> node-gyp rebuild


c:\dev\noble-master\node_modules\bluetooth-hci-socket>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules
\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
c:\dev\noble-master\node_modules\bluetooth-hci-socket\build\binding.sln : error MSB3411: Could not load the Visual C++ component "V
CBuild.exe". If the component is not installed, either 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Framew
ork 3.5, or 2) install Microsoft Visual Studio 2008.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v3.5\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\dev\noble-master\node_modules\bluetooth-hci-socket
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules\xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (cu
rrent: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules\bluetooth-hci-socket):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

Thanks for the great project!

**Comment by rasgo-xyz** [comment]
You need to install node-gyp. A bluetooth-hci-socket prerequisite:

https://github.com/sandeepmistry/node-bluetooth-hci-socket
https://github.com/nodejs/node-gyp#installation

**Comment by Xan-Kun** [comment]
A version of node-gyp was already present (I am not sure how) and I tried again from scratch, this time with an extra install node-gyp. It is still the same error message about the VS2008 compiler.

**Comment by Xan-Kun** [comment]
I made more trial and error and I think it has something to do with the gyp version, but I can't figure out what's wrong.

**Comment by Xan-Kun** [comment]
I THINK I just found the problem; I forgot to install .NET 4.5.1
I will try with a fresh install and see, if that really was all...

**Comment by Xan-Kun** [comment]
BTW, I think I forgot to install .NET because I used the video tutorial from Don Coleman and he uses VS, which automatically installs all the .NET stuff and the compiler. I wanted to go without VS and it works just fine :-)
