### ISSUE TITLE
Read / Send Values from Arduino + HM-10 to Raspberry Pi3

### ISSUE THREAD

**Issue by dasbenni** [sandeepmistry/noble#631]
Hello Gits, 

I want to use the Arduino + HM-10 to send strings and integers from my Arduino to my Raspberry Pi. 

With the examples advertisement-discovery.js and peripheral-explorer.js it is possible to connect to the BLE-Modul and get serviceuuid and so on. But I cannot send values from my Arduino to the Raspberry pi. You can find my Arduino-Code at the end.

I already tested it with the Arduino + HM-10 and my smartphone Ble Console – it works. 

Does anyone have a example-code for connecting receiving / sending values from a hm-10 to noble?

`#include <SoftwareSerial.h>

SoftwareSerial mySerial(7, 8); // RX, TX  
// Connect HM10      Arduino Uno
//     Pin 1/TXD          Pin 7
//     Pin 2/RXD          Pin 8

void setup() {  
  Serial.begin(9600);
  mySerial.begin(9600);
}

void loop() {  
  
  char c;
  if (Serial.available()) {
    c = Serial.read();
    mySerial.print(c);
  }
  if (mySerial.available()) {
    c = mySerial.read();
    Serial.print(c);   
  }

  //mySerial.print(0); Test
}`

**Comment by sandeepmistry** [comment]
Hi @dasbenni, I'd suggest you try something like [node-hm-ble](https://www.npmjs.com/package/node-hm-ble).
