### ISSUE TITLE
Apologies for creating an issue, new to github and not sure how to ask a question!

### ISSUE THREAD

**Issue by davidcreager** [sandeepmistry/noble#632]
Your code is brilliant.  Thank you for sharing.

I have written a node.js server that connects to bt devices....it works fine but stops scanning after a bit.  What is it that causes noble to stop scanning?

I receive the stopScan event....just have no idea what triggers it.

I worked around by just starting a scan every 15 secs if necessary.

I am running on a Raspberry Pi 3 with Raspbian Jessie......all installed fine and works apart from this

**Comment by jrobeson** [comment]
read through some of the other bugs. Some adapters won't let you connect while scanning (and perhaps vice versa).  try to stop scanning while connected.

**Comment by davidcreager** [comment]
Thanks  Apologies if I failed at researching thoroughly.   Appreciate your time in answering
