### ISSUE TITLE
Error: Cannot find module 'bluetooth-hci-socket'

### ISSUE THREAD

**Issue by nikoc03** [sandeepmistry/noble#633]
Hello everyone I installed node.js and npm and I am trying to run btlejuice-proxy as it is displayed in the github repo. Although I keep getting the same errors 

```

> module.js:487
>     throw err;
>     ^
> 
> Error: Cannot find module 'bluetooth-hci-socket'
>     at Function.Module._resolveFilename (module.js:485:15)
>     at Function.Module._load (module.js:437:25)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/root/local/lib/node_modules/btlejuice/node_modules/noble/lib/hci-socket/hci.js:6:26)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)

```

Then I tried to install bluetooth-hci-socket using npm install bluetooth-hci-socket but I got the following errors:

> >module.js:487
>     throw err;
>     ^
> 
> Error: Cannot find module 'bluetooth-hci-socket'
>     at Function.Module._resolveFilename (module.js:485:15)
>     at Function.Module._load (module.js:437:25)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/root/local/lib/node_modules/btlejuice/node_modules/noble/lib/hci-socket/hci.js:6:26)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)
> root@hellothere:~# npm install bluetooth-hci-socket
> 
> > bluetooth-hci-socket@0.5.1 install /root/node_modules/bluetooth-hci-socket
> > node-gyp rebuild
> 
> gyp ERR! configure error 
> gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
> gyp ERR! stack     at install (/root/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:66:16)
> gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/root/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:55:37)
> gyp ERR! stack     at getNodeDir (/root/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:77:20)
> gyp ERR! stack     at PythonFinder.callback (/root/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:44:7)
> gyp ERR! stack     at PythonFinder.<anonymous> (/root/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:470:14)
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:262:7)
> gyp ERR! stack     at emitTwo (events.js:125:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
> gyp ERR! stack     at maybeClose (internal/child_process.js:897:16)
> gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:340:11)
> gyp ERR! System Linux 4.9.0-kali4-amd64
> gyp ERR! command "/root/local/bin/node" "/root/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /root/node_modules/bluetooth-hci-socket
> gyp ERR! node -v v9.0.0-pre
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok 
> npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
> npm WARN root No description
> npm WARN root No repository field.
> npm WARN root No README data
> npm WARN root No license field.
> npm WARN You are using a pre-release version of node and things may not work as expected
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the bluetooth-hci-socket@0.5.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2017-06-11T15_30_39_207Z-debug.log

Could someone help me please?

**Comment by sandeepmistry** [comment]
@nikoc03 I suggest trying again with an older version of Node.js `node -v v9.0.0-pre` seems very bleeding edge.
