### ISSUE TITLE
using multiple bluetooth adapters at the same time

### ISSUE THREAD

**Issue by trungpham** [sandeepmistry/noble#639]
I need to connect to ten bluetooth devices, but a single bluetooth adapter can only support five devices. So I will need to use two bluetooth adapters to be able to connect to all ten bluetooth devices.

Is there a way to control multiple bluetooth adapters within the same node script? Or should I fork a second node process with a different NOBLE_HCI_DEVICE_ID environment variable, and pass messages between the two different node processes? Thanks.

**Comment by sandeepmistry** [comment]
@trungpham forking a process is the current recommended way.
