### ISSUE TITLE
Supported USB Dongles for OSX

### ISSUE THREAD

**Issue by Keped** [sandeepmistry/noble#641]
This truly amazing library works smoothly on windows with a CSR8510A10 dongle, and also on OSX using the built in BLE. However, the mentioned dongle does not work consistently on older Apple machines that don't have BLE 4.0
The link in https://github.com/sandeepmistry/noble/wiki/Compatible-devices#bluetooth-40-usb-adapters is broken and leads to an error page...

**Comment by sandeepmistry** [comment]
@Keped I've removed the link from wiki. 

> However, the mentioned dongle does not work consistently on older Apple machines that don't have BLE 4.0

This is most likely an issue with CoreBluetooth/blued on which noble relies on. Closing as those are maintained by Apple and there's nothing we can really do here unfortunately ...
