### ISSUE TITLE
node-pre-gyp ERR! Pre-built binaries not found for usb@1.2.0 and node@5.11.1 (node-v47 ABI) (falling back to source compile with node-gyp)

### ISSUE THREAD

**Issue by matak** [sandeepmistry/noble#644]
hi, 

on centos 6 i am not abble to install usb package, npm-debug.log in attachment

anybody knows what could be the problem?

[npm-debug.txt](https://github.com/sandeepmistry/noble/files/1114970/npm-debug.txt)

**Comment by sandeepmistry** [comment]
@matak I suggest you follow up on this here: https://github.com/tessel/node-usb
