### ISSUE TITLE
Dealing with large packets

### ISSUE THREAD

**Issue by Edylc** [sandeepmistry/noble#647]
Hi,

I'm new to BLE, but I got the impression that noble and bleno would automatically handle packets larger than the MTU by splitting them up; however, when I write something more than 512B, the peripheral will not receive anything and the central does not find any errors.  Could you help me figure out what's going on?

Thanks.

**Comment by sandeepmistry** [comment]
@Edylc from what I recall from the specification, characteristics can only have a maximum size of 512 bytes.
