### ISSUE TITLE
How can i get Characteristic's handle value?

### ISSUE THREAD

**Issue by LanFly** [sandeepmistry/noble#655]
I want to send a Alert command to the smart bracelet, and I'll write the following code:
```js
peripheral.writeHandle(Buffer.from([0x53]), Buffer.from([0x01]), true, function(error){
    console.log('Alert MI 1A');
})
```
The UUID of the IMMEDIATE ALERT service is **0x1800**, and the UUID of the ALERT LEVEL characteristic is **0x2a06**. So how did **0x53** get it? Where should I get it?

**Comment by sandeepmistry** [comment]
@LanFly there are no API's to access the handles. I strongly suggest discovering services and characteristic instead.
