### ISSUE TITLE
services (and uuid?) of peripheral different between macos and linux

### ISSUE THREAD

**Issue by chee** [sandeepmistry/noble#657]
this: `(linux)`
![linux](https://user-images.githubusercontent.com/178266/28484447-5192d2b4-6e6a-11e7-909f-7b5d2a24871c.png)

and this: `(macOS)`
![macOS](https://user-images.githubusercontent.com/178266/28484457-5cd06eac-6e6a-11e7-811e-149910c8e97f.png)

are the same peripheral, a Bluetooth Low Energy lightbulb. but when querying it from Linux i get 4 services, while i only see 3 on the macOS side.
they also both have a different value for uuid? perhaps this is normal, i don't have any other BLE devices around here to talk to, it's just me and the blub.
both are using the same version of noble, the Linux side is `arch linux arm` on a Raspberry Pi 3.

it's the same small script on both machines, which you can find in the comment below.

**Comment by chee** [comment]
```js
const noble = require('noble')

noble.on('stateChange', state =>
  state === 'poweredOn' && discover())

const discover = () => {
  noble.on('discover', peripheral => {
    if (peripheral.address !== '00:21:4d:03:20:1b') return
    noble.stopScanning()
    console.log(peripheral.uuid)
    peripheral.connect(() => interrogate(peripheral))
  })

  noble.startScanning()
}

const interrogate = peripheral =>
  peripheral.discoverAllServicesAndCharacteristics(() => console.log(list(peripheral)))

const list = peripheral =>
 peripheral.services.map((service, index) =>
   `${index}. ${service.uuid}`
 ).join('\n')
```

**Comment by sandeepmistry** [comment]
@chee macOS blocks the `1800` service. It's better to compare the UUID's.

**Comment by chee** [comment]
thank you a lot, that has worked fine. i now can control my bluetooth bulbs with my javascript computer.
