### ISSUE TITLE
Can connect Mac to Sphero Ollie once, but never again

### ISSUE THREAD

**Issue by dizzybird** [sandeepmistry/noble#671]
I've been using two Sphero Ollie devices for a few months, through Android phone and tablet: Ollie app, Tynker, Sphero Edu.  All connect/work fine.

I just tried cylon, and  was able to connect to Ollie from my Macbook Air (2015, running Sierra)... cylon uses noble for connections, right?  I ran the cylon-sphero-ble/examples/color/color.js example code, and it changed the colors on Ollie.  Yay.

But after that one successful run, I can no longer connect to Ollie... not from cylon, not from straight noble, not from any of the Android apps.

Ollie's charging light shows green when when USB is plugged in.
And I still see Ollie's name/UUID when running advertisement-discovery.js.
And I still see Ollie listed in peripheral-explorer.js output.... but there's empty services/characteristics.
But otherwise it's dead... I cannot connect to it.

And here's the thing: the exact same thing happened on both of my Ollie devices: connected through cylon/noble once, but thereafter I cannot connect.

Seems like it could be a problem with Ollie firmware.... but seems to have been bonked from running cylon/noble... ?

Contacted Sphero support, no info yet.

Any help/advice appreciated.

**Comment by sandeepmistry** [comment]
@dizzybird I suggest you engage the `cylon-sphero-ble` maintainers first, this is not likely caused directly by noble.
