### ISSUE TITLE
Multiple instances in Windows problem

### ISSUE THREAD

**Issue by jsantos98** [sandeepmistry/noble#687]
Hi,

While trying to have multiple instances of a noble connection, I'm always getting an exception.

To reproduce:
1. Open a command window
2. browse to the examples folder
3. run "node advertisement-discovery.js"
4. Leave that window running, open a new one
5. Browse again to the examples folder
6. Run the same "node advertisement-discovery.js"

I'm getting the following exception:

> ...\node_modules\usb\usb.js:33
>         this.__open()
>              ^
> 
> Error: LIBUSB_ERROR_ACCESS
>     at Error (native)
>     at Device.usb.Device.open (...\node_modules\usb\usb.js:33:7)
>     at BluetoothHciSocket.bindUser (...\node_modules\bluetooth-hci-socket\lib\usb.js:73:19)
>     at Hci.init (...\node_modules\noble\lib\hci-socket\hci.js:96:35)
>     at NobleBindings.init (...\node_modules\noble\lib\hci-socket\bindings.js:82:13)
>     at new Noble (...\node_modules\noble\lib\noble.js:50:18)
>     at Object.<anonymous> (...\node_modules\noble\index.js:4:18)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
> 

Any idea how to bypass this?

Thanks

**Comment by lemmerelassal** [comment]
With LibUSB you can only claim the interface once.

**Comment by jsantos98** [comment]
I was already suspecting for a restriction like that :(

Is there any workaround to support multiple instances?

Regards
Joao

**Comment by lemmerelassal** [comment]
Oh, you want to connect to multiple devices via one dongle, eh?
This is doable using one script alone!

**Comment by sandeepmistry** [comment]
@jsantos98 use multiple USB adapters.

@lemmerelassal thanks for helping out!
