### ISSUE TITLE
Nothing happens once examples are run

### ISSUE THREAD

**Issue by simonem** [sandeepmistry/noble#704]
Just installed noble on OSX High Sierra.
Tried to run the example but nothing shows up launching advertisement-discovery.js or enter-exit.js
I get a "Cannot read property 'toLowerCase' of undefined" launching peripheral-explorer.js
I have a few BTLE devices (RFDUINO and nRF52) discoverable nearby.

Thanks
Simone

**Comment by fivdi** [comment]
@simonem 

> I get a "Cannot read property 'toLowerCase' of undefined" launching peripheral-explorer.js
I have a few BTLE devices (RFDUINO and nRF52) discoverable nearby.

A `Cannot read property 'toLowerCase' of undefined` error is thrown when no peripheral ID or address is passed on the command-line when running peripheral-explorer.js.

Passing a peripheral address on the command-line looks something like this:
```
sudo node peripheral-explorer.js 12:34:56:78:9A:BC
```
Passing a peripheral ID on the command-line looks something like this:
```
sudo node peripheral-explorer.js 123456789ABC
```

**Comment by simonem** [comment]
@fivdi Thank you!
