### ISSUE TITLE
Can you select bluetooth adapter in OS X/Windows?

### ISSUE THREAD

**Issue by NAllred91** [sandeepmistry/noble#706]
I see there is a way to select the specific bluetooth adapter you want to use on linux.  Is there any similar functionality on OS X/Windows?

**Comment by chnd** [comment]
I don't know on Windows, but On OS X it is possible to select a specific bluetooth adapter by using bluetooth explorer app (Open from menu Tools, HCI Controller Selector). The app is part of Hardware IO Tools for XCode. You may need an Apple developer ID (free registration) to download the tool from the Apple Developer website.

**Comment by sandeepmistry** [comment]
Please see: https://github.com/sandeepmistry/node-bluetooth-hci-socket#windows-1 for windows.
