### ISSUE TITLE
Not working after macOS High Sierra Upgrade

### ISSUE THREAD

**Issue by dlarendt** [sandeepmistry/noble#709]
Noble was working on my system recently, but it is no longer working after I upgraded to macOS High Sierra this morning. Running examples/advertisement-discovery.js produces no output. I am sure there are bluetooth devices in range. Any ideas on how to start troubleshooting this?

**Comment by bennesp** [comment]
The same is happening to me, with Apple Bluetooth Explorer I can see many BLE devices, but advertisement-discovery.js shows me nothing

**Comment by dlarendt** [comment]
Yep, worked for me too.

**Comment by jguillod** [comment]
Dont work for me under High Sierra !!
Was working perfectly just before !

**Comment by jacobrosenthal** [comment]
Duplicate of #679
