### ISSUE TITLE
Issue Including Noble when running with Sudo 

### ISSUE THREAD

**Issue by fallenfate1982** [sandeepmistry/noble#711]
I have Noble running find with Homebridge. I'm writing another Nodejs application which needs to use noble. However, when I run this application with sudo it does not find noble. 

Everything is being run on a rPi3B

See screen shot

Thoughts?
![screen shot 2017-11-19 at 6 10 42 pm](https://user-images.githubusercontent.com/11913442/32996144-4d999ea0-cd55-11e7-9900-3e57190d67d5.png)

**Comment by sandeepmistry** [comment]
The sudo node module path is not the same as the regular, I suggest you make them the same.
