### ISSUE TITLE
macOS speed

### ISSUE THREAD

**Issue by gpgabriel** [sandeepmistry/noble#715]
Hi,

I have a nRF52832 board which defines 3 notify characteristics and each of them is emitting random numbers every 50 milliseconds.

https://gist.github.com/gpgabriel/f6e69c437cf5449c847f290beacdf095

When I run the script above on a `RaspberryPi3` (node v8.4.0) I get constant `... 20 20 20` which makes sense and is what I'm looking for but when I run the exact same script on a `macOS 10.12.6` (node v8.4.0) I get `... 10 0 12`, `... 7 2 8`, `... 9 0 12` which is not very useful as I need constant 20fps.

Is there any known issue with the performance on macOS? Is there any known way to optimize for this case?

Gabriel

EDIT: On macOS If I subscribe to only 1/3 characteristics then I get all the 20 expected frames.

**Comment by sandeepmistry** [comment]
This is all based on Apple's CoreBluetooth and blued daemon, not much we can do.
