### ISSUE TITLE
Can't install noble correctly

### ISSUE THREAD

**Issue by Kepete** [sandeepmistry/noble#740]
I need noble for a plugin, but can't figure out how to install it correctly. 
I have tried command `sudo npm install noble` and it didn't install it at all. Then I tried it using root user and got this output: 

<img width="1280" alt="screen shot 2018-01-24 at 20 41 18" src="https://user-images.githubusercontent.com/32489848/35350598-179cc7ac-0147-11e8-8f26-e1b38ecb0aec.png">

the plugin what needs it runs into an error and this is because of noble is installed incorrectly.

**Comment by Kepete** [comment]
I also tried the command `sudo npm install -g --unsafe-perm noble`
It kind of worked, but my plugin what needs noble still says that it is incorrectly installed. 

<img width="924" alt="screen shot 2018-01-25 at 10 56 59" src="https://user-images.githubusercontent.com/32489848/35379641-67b724a8-01bf-11e8-8b7f-46c789a0bc84.png">

**Comment by M1ras** [comment]
I've run into this issue as well, it looks like the USB bindings don't play nice with Node 9.X. Try reinstalling with Node 8.X LTS (it's what fixed it for me).

**Comment by sandeepmistry** [comment]
It's an optional dependency on Linux so this is fine, `node-bluetooth-hci-socket` has 1.x of node-usb in package.json and 1.4.0 is the latest release. Will have to wait for upstream to fix node 9 stuff.
