### ISSUE TITLE
Why am I getting different UUID when I run in App from running it directly in noble/example/advertisement.js?

### ISSUE THREAD

**Issue by NaseebullahSafi** [sandeepmistry/noble#748]
In my App, I'm trying to connect to an arduino that is shipped with a dongle using noble.

I've followed this [`step`](https://github.com/sandeepmistry/noble#windows)

When I run it in noble/example/advertisement.js, it returns the following:
<img width="928" alt="capture" src="https://user-images.githubusercontent.com/16179773/35704107-3878494c-0796-11e8-8b25-3d6b1d266b92.PNG">

But when I try to search it in my App, I get the following:

<img width="1063" alt="capture" src="https://user-images.githubusercontent.com/16179773/35704089-2e5553ec-0796-11e8-8164-d336a48a3caf.PNG">

This is a big issue because I cant connect to my arduino.

My services UUID should be 4 digits long for example:

Should be
=
```
1800
1801
2220
```
Not:
=
```
0000180000001....
0000180100001....
0000222100001....
```

Why is this happening?

Edit
=
I don't have Bluetooth adapter, there's already Bluetooth installed on my laptop, which I used Zadid and installed WinUSB driver for it.

Edit
=
I just ran my app in iphone, and it's giving me the expected result:
ie.:
```
1800
1801
2220
```

but in android, its giving me the longer version. How can I change this?

**Comment by NaseebullahSafi** [comment]
Any ideas? @sandeepmistry

**Comment by sandeepmistry** [comment]
Please don't open multiple issues. https://github.com/jacobrosenthal/react-native-ble/issues/58.
