### ISSUE TITLE
Changing the Connection Interval

### ISSUE THREAD

**Issue by czednick** [sandeepmistry/noble#83]
Is it possible via Noble to change the BLE connection interval? Thanks in advance!

**Comment by rosek86** [comment]
@sandeepmistry If you consider to merge this PR, I'd need to check default parameters which bluez uses first. Let me know if you have any comment regarding l2capBle part. Thanks

**Comment by sandeepmistry** [comment]
@rosek86 how were you thinking setting the connection interval will work?

I'd prefer if it was handled in the same way OS X does it (I don't know the specifics). Having a Linux only API is an option, then apps will not be cross platform if they use it.

**Comment by rosek86** [comment]
@sandeepmistry in the next step we could add e.g. setConnectionParams function in NobleBindings & Noble. The setConnectionParams would accept values in milliseconds and then these values will be translated into platform specific values in NobleBindings. I believe that these params should be a standard for all platforms as they're well described in the Bluetooth 4 specification (I may be wrong here, though). 

I don't know how this can be implemented under OS X (I'm not a mac user, sorry) but we could throw an exception ('not implemented') in bindings, where connection parameters configuration hasn't been implemented yet.

Users has two options then,-

1. try to set connection parameters and handle 'non implemented' exception,
2. check the platform and update connection intervals only when it's supported by noble.

I think this solution shouldn't cause any problems for users if the feature is well documented, the example would be useful too (which I can prepare if we'll go for it).

I believe that this feature would be very useful for users, e.g. in our application we have to download quickly 18 kB of data, only by changing connection parameters (to 7.5 ms) download time reduced from around 20 seconds to around 3.

Unfortunately the Bluetooth LE module installed on Intel Edison doesn't support 'multiple packets per connection event' by default, if this would be supported we could reduce download time by 6...

**Comment by sandeepmistry** [comment]
@rosek86 I'd like to better understand how OS X handles this before moving forward. There is no API call in CoreBluetooth to set the connection interval. I'm wondering if it picks something based on the [Peripheral Preferred Connection Parameters](https://developer.bluetooth.org/gatt/characteristics/Pages/CharacteristicViewer.aspx?u=org.bluetooth.characteristic.gap.peripheral_preferred_connection_parameters.xml) characteristic.

**Comment by rosek86** [comment]
@sandeepmistry I've found apple's 'bluetooth design guidelines', p.22 'Connection Paremeters':
https://developer.apple.com/hardwaredrivers/BluetoothDesignGuidelines.pdf

It seems that on Mac the accessory is responsible for connection parameters:

"The accessory isresponsible for the connection parameters used for the Low Energy connection. The accessory should request connection parameters appropriate for its use case by sending an L2CAP Connection Parameter Update Request at the appropriate time"

It's not what I'd expect, but I think that's a possible solution for our peripherals too.

**Comment by sandeepmistry** [comment]
@rosek86 thanks for looking into this!

So it's sounding like we don't need an API to set the connection interval if we let the peripheral decide?

**Comment by rosek86** [comment]
@sandeepmistry Yes, this means that the connection parameters logic is moved from a central to a peripheral. Personally we'd need to modify peripheral devices to request certain connection intervals and update these intervals when condition changes (for instance we need shorter connection intervals during data transmission but longer intervals during DFU).

The peripheral device can set min & max interval to the same value (e. g. 7.5 ms) and central will accept this.

**Comment by sandeepmistry** [comment]
@rosek86 that sounds good. Closing this issue then.
